# THIS FILE WAS AUTO-GENERATED BY generate_units.py. DO NOT MODIFY

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import override, Any, TYPE_CHECKING
from smartunits import Measure, Unit

if TYPE_CHECKING:
        from smartunits import EquivalentDoseUnit 

@dataclass(frozen=True, slots=True)
class EquivalentDose(Measure["EquivalentDoseUnit"], ABC):
    _magnitude: float
    _base_unit_magnitude: float
    _unit: "EquivalentDoseUnit"

    @staticmethod
    def of(magnitude: float, unit: "EquivalentDoseUnit") -> "EquivalentDose":
        return EquivalentDose(magnitude, unit.to_base_units(magnitude), unit)

    @staticmethod
    def of_base_units(base_unit_magnitude: float, unit: "EquivalentDoseUnit") -> "EquivalentDose":
        return EquivalentDose(unit.from_base_units(base_unit_magnitude), base_unit_magnitude, unit)

    @override
    def magnitude(self) -> float:
        return self._magnitude

    @override
    def base_unit_magnitude(self) -> float:
        return self._base_unit_magnitude
    
    @override
    def unit(self) -> "EquivalentDoseUnit":
        return self._unit

    @override
    def base_unit(self) -> "EquivalentDoseUnit":
        return self._unit._base_unit

    @override
    def into(self, unit: "EquivalentDoseUnit") -> "EquivalentDoseUnit":
        if unit is self._unit:
            return self._magnitude
        return "EquivalentDoseUnit".of(unit.from_base_units(self._base_unit_magnitude))

    @override
    def in_unit(self, unit: "EquivalentDoseUnit") -> float:
        if unit is self._unit:
            return self._magnitude
        return unit.from_base_units(self._base_unit_magnitude)

    @override
    def in_units(self, unit: "EquivalentDoseUnit") -> float:
        if unit is self._unit:
            return self._magnitude
        return unit.from_base_units(self._base_unit_magnitude)
    
    @override
    def __neg__(self) -> "EquivalentDose":
        return EquivalentDose(-self._magnitude, -self._base_unit_magnitude, self._unit)
    
    @override
    def __add__(self, other: Measure["EquivalentDoseUnit"]) -> "EquivalentDose":
        if self._unit is other._unit:
            return EquivalentDose(self._magnitude + other._magnitude, self._base_unit_magnitude + other._magnitude, self._unit)
        
        return self._unit.of_base_units(self._base_unit_magnitude + other._base_unit_magnitude)
    
    @override
    def __sub__(self, other: Measure["EquivalentDoseUnit"]) -> "EquivalentDose":
        if self._unit is other._unit:
            return EquivalentDose(self._magnitude - other._magnitude, self._base_unit_magnitude, self._unit)
        
        return self._unit.of_base_units(self._base_unit_magnitude - other._base_unit_magnitude)

    def __mul__(self, other: Any) -> Measure[Any]:
        # handles scalar
        if isinstance(other, (int, float)):
                return EquivalentDose(self._magnitude * other, self._base_unit_magnitude * other, self._unit)

        # handles EquivalentDose
        if isinstance(other, EquivalentDose):
                return self.of_base_units(self._base_unit_magnitude * other._base_unit_magnitude)

        # handle Dimensionless
        from smartunits.measures import Dimensionless
        if isinstance(other, Dimensionless):
                factor = other._base_unit_magnitude
                return EquivalentDose(self._magnitude * factor, self._base_unit_magnitude * factor, self._unit)

        # handle unit-specific multiply implementations

        # fallback generic
        base_result = self._base_unit_magnitude * other._base_unit_magnitude
        other_unit = other._unit

        # handle PerUnit and MultUnit
        from smartunits.measures import PerUnit
        if isinstance(other_unit, PerUnit):
                if self._unit._base_unit == other_unit._denominator._base_unit:
                        return other_unit._numerator.from_base_units(base_result)

        # fallback to MultUnit
        from smartunits.measure import MultUnit
        return MultUnit.combine(self._unit, other_unit).of_base_units(base_result)

    def __truediv__(self, other: Any) -> Measure[Any]:
        if isinstance(other, (int, float)):
            return EquivalentDose(self._magnitude / other, self._base_unit_magnitude / other, self._unit)

        # handles EquivalentDose
        if isinstance(other, EquivalentDose):
            return self._base_unit_magnitude / other._base_unit_magnitude

        # handle Dimensionless
        from smartunits.measures import Dimensionless
        if isinstance(other, Dimensionless):
            factor = other._base_unit_magnitude
            return EquivalentDose(self._magnitude / factor, self._base_unit_magnitude / factor, self._unit)

        base_result = self._base_unit_magnitude / other._base_unit_magnitude

        from smartunits.measures import PerUnit
        return PerUnit.combine(self._unit, other._unit).of_base_units(base_result)

    def __str__(self) -> str:
        return f"{self._magnitude:.3e} {self._unit._symbol}"

