# Copyright (c) FIRST and other WPILib contributors.
# Open Source Software; you can modify and/or share it under the terms of
# the WPILib BSD license file in the root directory of this project.

# THIS FILE WAS AUTO-GENERATED BY generate_units.py. DO NOT MODIFY

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import override, Any, TYPE_CHECKING, Generic, TypeVar
from smartunits import Measure

Dividend = TypeVar('Dividend', bound=Unit)
Divisor = TypeVar('Divisor', bound=Unit)
if TYPE_CHECKING:
    from smartunits import PerUnit 

@dataclass(frozen=True, slots=True)
class Per(Measure["PerUnit[Dividend, Divisor]"], ABC, Generic[Dividend, Divisor]):
  _magnitude: float
  _base_unit_magnitude: float
  _unit: "PerUnit[Dividend, Divisor]"

  @staticmethod
  def of(magnitude: float, unit: "PerUnit[Dividend, Divisor]") -> "Per[Dividend, Divisor]":
    return Per[Dividend, Divisor](magnitude, unit.to_base_units(magnitude), unit)

  @staticmethod
  def of_base_units(base_unit_magnitude: float, unit: "PerUnit[Dividend, Divisor]") -> "Per[Dividend, Divisor]":
    return Per[Dividend, Divisor](unit.from_base_units(base_unit_magnitude), base_unit_magnitude, unit)

  @override
  def magnitude(self) -> float:
    return self._magnitude

  @override
  def base_unit_magnitude(self) -> float:
    return self._base_unit_magnitude
  
  @override
  def unit(self) -> "PerUnit[Dividend, Divisor]":
    return self._unit

  @override
  def base_unit(self) -> "PerUnit[Dividend, Divisor]":
    return self._unit._base_unit

  def in_units(self, unit: "PerUnit[Dividend, Divisor]") -> float:
    if unit is self._unit:
      return self._magnitude
    return unit.from_base_units(self._base_unit_magnitude)
  
  @override
  def __neg__(self) -> "Per[Dividend, Divisor]":
    return Per[Dividend, Divisor](-self._magnitude, -self._base_unit_magnitude, self._unit)
  
  @override
  def __add__(self, other: Measure["PerUnit[Dividend, Divisor]"]) -> "Per[Dividend, Divisor]":
    if self._unit is other._unit:
      return Per[Dividend, Divisor](self._magnitude + other._magnitude, self._base_unit_magnitude + other._magnitude, self._unit)
    
    return self._unit.of_base_units(self._base_unit_magnitude + other._base_unit_magnitude)
  
  @override
  def __sub__(self, other: Measure["PerUnit[Dividend, Divisor]"]) -> "Per[Dividend, Divisor]":
    if self._unit is other._unit:
      return Per[Dividend, Divisor](self._magnitude - other._magnitude, self._base_unit_magnitude, self._unit)
    
    return self._unit.of_base_units(self._base_unit_magnitude - other._base_unit_magnitude)

  def __mul__(self, other: Any) -> Measure[Any]:
    # handles scalar
    if isinstance(other, (int, float)):
        return Per[Dividend, Divisor](self._magnitude * other, self._base_unit_magnitude * other, self._unit)

    # handles Per[Dividend, Divisor]
    if isinstance(other, Per[Dividend, Divisor]):
        return self.of_base_units(self._base_unit_magnitude * other._base_unit_magnitude)

    # handle Dimensionless
    from smartunits.measures import Dimensionless
    if isinstance(other, Dimensionless):
        factor = other._base_unit_magnitude
        return Per[Dividend, Divisor](self._magnitude * factor, self._base_unit_magnitude * factor, self._unit)

    # handle unit-specific multiply implementations
    # fallback generic
    base_result = self._base_unit_magnitude * other._base_unit_magnitude
    other_unit = other._unit

    # handle PerUnit and MultUnit
    from smartunits.measures import PerUnit
    if isinstance(other_unit, PerUnit):
        if self._unit._base_unit == other_unit._denominator._base_unit:
            return other_unit._numerator.from_base_units(base_result)

    # fallback to MultUnit
    from smartunits.measure import MultUnit
    return MultUnit.combine(self._unit, other_unit).of_base_units(base_result)

  def __truediv__(self, other: Any) -> Measure[Any]:
    if isinstance(other, (int, float)):
      return Per[Dividend, Divisor](self._magnitude / other, self._base_unit_magnitude / other, self._unit)

    # handles Per
    if isinstance(other, Per[Dividend, Divisor]):
        return (self._base_unit_magnitude / other._base_unit_magnitude)

    # handle Dimensionless
    from smartunits.measures import Dimensionless
    if isinstance(other, Dimensionless):
      factor = other._base_unit_magnitude
      return Per[Dividend, Divisor](self._magnitude / factor, self._base_unit_magnitude / factor, self._unit)

    base_result = self._base_unit_magnitude / other._base_unit_magnitude

    from smartunits.measures import PerUnit
    return PerUnit.combine(self._unit, other._unit).of_base_units(base_result)

  def __str__(self) -> str:
    return f"{self._magnitude:.3e} {self._unit._symbol}"

  def times_divisor(self, multiplier: Measure[Divisor]) ->  Measure[Dividend]: {
      return self._base_unit._numerator.of_base_units(self._base_unit_magnitude * multiplier._base_unit_magnitude);
}

def reciprocal(self) -> PerUnit[Divisor, Dividend]:
      # May return a velocity if Divisor == TimeUnit, so we can't guarantee a "Per" instance
      return self._base_unit.reciprocal().of_base_units(1 / self._base_unit_magnitude)
}