# THIS FILE WAS AUTO-GENERATED BY generate_units.py. DO NOT MODIFY

from typing import override

from smartunits import Unit, UnaryFunction
from smartunits.measures.angle import Angle



class AngleUnit(Unit):
    __slots__ = (
        "_to_base_multiplier",
        "_to_base_offset",
        "_from_base_multiplier",
        "_from_base_offset",
    )
    _base_unit: "AngleUnit"
    _to_base_multiplier: float
    _to_base_offset: float
    _from_base_multiplier: float
    _from_base_offset: float

    def __init__(
        self,
        base_unit: "AngleUnit",
        to_base_multiplier: float,
        to_base_offset: float,
        from_base_multiplier: float,
        from_base_offset: float,
        name: str,
        symbol: str,
    ) -> None:
        super().__init__(base_unit, name, symbol)
        self._to_base_multiplier = to_base_multiplier
        self._to_base_offset = to_base_offset
        self._from_base_multiplier = from_base_multiplier
        self._from_base_offset = from_base_offset

    @override
    def get_base_unit(self) -> "AngleUnit":
        return self._base_unit

    @override
    def of(self, magnitude: float):
        return Angle.of(magnitude, self)

    @override
    def of_base_units(self, magnitude: float):
        return Angle.of_base_units(magnitude, self)

    @override
    def zero(self):
        return self._zero

    @override
    def one(self):
        return self._one

    @override
    def per(self, other: Unit) -> Unit:
        t = type(other)
        from .time_unit import TimeUnit
        if t is TimeUnit:
            from .angular_velocity_unit import AngularVelocityUnit
            return AngularVelocityUnit.combine(self, other)

        from smartunits import PerUnit
        return PerUnit[AngleUnit, t].combine(self, other)

    def __mul__(self, other: Unit) -> Unit:
        t = type(other)

        return NotImplemented

    @override
    def convert_from(self, magnitude: float, other_unit: "AngleUnit") -> float:
        return self.from_base_units(other_unit.to_base_units(magnitude))

    @override
    def convert_to(self, magnitude: float, other_unit: "AngleUnit") -> float:
        return other_unit.from_base_units(self.to_base_units(magnitude))

    @override
    def conversion_from(self, other_unit: "AngleUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(other_unit.to_base_units(x)))

    @override
    def conversion_to(self, other_unit: "AngleUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: other_unit.from_base_units(self.to_base_units(x)))

    @override
    def from_base_units(self, value_in_base_units: float) -> float:
        return value_in_base_units * self._from_base_multiplier + self._from_base_offset

    @override
    def to_base_units(self, value_in_native_units: float) -> float:
        return value_in_native_units * self._to_base_multiplier + self._to_base_offset

    @override
    def conversion_from_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(x))

    @override
    def conversion_to_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.to_base_units(x))


radians = AngleUnit(None, 1.0, 0.0, 1.0, -0.0, "radian", "rad")
revolutions = AngleUnit(radians, 6.283185307179586, 0.0, 0.15915494309189535, -0.0, "revolution", "R")
rotations = AngleUnit(radians, 6.283185307179586, 0.0, 0.15915494309189535, -0.0, "rotation", "R")
degrees = AngleUnit(radians, 0.017453292519943295, 0.0, 57.29577951308232, -0.0, "degree", "°")
nanoradians = AngleUnit(radians, 1e-09, 0.0, 999999999.9999999, -0.0, "nanoradians", "nanoradians")
microradians = AngleUnit(radians, 1e-06, 0.0, 1000000.0, -0.0, "microradians", "microradians")
milliradians = AngleUnit(radians, 0.001, 0.0, 1000.0, -0.0, "milliradians", "milliradians")
kiloradians = AngleUnit(radians, 1000.0, 0.0, 0.001, -0.0, "kiloradians", "kiloradians")
arcminutes = AngleUnit(radians, 0.0002908882086657216, 0.0, 3437.7467707849396, -0.0, "arcminutes", "arcminutes")
arcseconds = AngleUnit(radians, 4.84813681109536e-06, 0.0, 206264.80624709636, -0.0, "arcseconds", "arcseconds")
milliarcseconds = AngleUnit(radians, 4.8481368110953594e-09, 0.0, 206264806.2470964, -0.0, "milliarcseconds", "milliarcseconds")
turns = AngleUnit(radians, 6.283185307179586, 0.0, 0.15915494309189535, -0.0, "turns", "turns")
gradians = AngleUnit(radians, 0.015707963267948967, 0.0, 63.66197723675813, -0.0, "gradians", "gradians")

__all__ = ["AngleUnit", "radians", "revolutions", "rotations", "degrees", "nanoradians", "microradians", "milliradians", "kiloradians", "arcminutes", "arcseconds", "milliarcseconds", "turns", "gradians"]
