# THIS FILE WAS AUTO-GENERATED BY generate_units.py. DO NOT MODIFY

from typing import override

from smartunits import Unit, UnaryFunction
from smartunits.measures.angular_acceleration import AngularAcceleration



class AngularAccelerationUnit(Unit):
    __slots__ = (
        "_to_base_multiplier",
        "_to_base_offset",
        "_from_base_multiplier",
        "_from_base_offset",
    )
    _base_unit: "AngularAccelerationUnit"
    _to_base_multiplier: float
    _to_base_offset: float
    _from_base_multiplier: float
    _from_base_offset: float

    def __init__(
        self,
        base_unit: "AngularAccelerationUnit",
        to_base_multiplier: float,
        to_base_offset: float,
        from_base_multiplier: float,
        from_base_offset: float,
        name: str,
        symbol: str,
    ) -> None:
        super().__init__(base_unit, name, symbol)
        self._to_base_multiplier = to_base_multiplier
        self._to_base_offset = to_base_offset
        self._from_base_multiplier = from_base_multiplier
        self._from_base_offset = from_base_offset

    @override
    def get_base_unit(self) -> "AngularAccelerationUnit":
        return self._base_unit

    @override
    def of(self, magnitude: float):
        return AngularAcceleration.of(magnitude, self)

    @override
    def of_base_units(self, magnitude: float):
        return AngularAcceleration.of_base_units(magnitude, self)

    @override
    def zero(self):
        return self._zero

    @override
    def one(self):
        return self._one

    @override
    def per(self, other: Unit) -> Unit:
        t = type(other)

        from smartunits import PerUnit
        return PerUnit[AngularAccelerationUnit, t].combine(self, other)

    def __mul__(self, other: Unit) -> Unit:
        t = type(other)

        return NotImplemented

    @override
    def convert_from(self, magnitude: float, other_unit: "AngularAccelerationUnit") -> float:
        return self.from_base_units(other_unit.to_base_units(magnitude))

    @override
    def convert_to(self, magnitude: float, other_unit: "AngularAccelerationUnit") -> float:
        return other_unit.from_base_units(self.to_base_units(magnitude))

    @override
    def conversion_from(self, other_unit: "AngularAccelerationUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(other_unit.to_base_units(x)))

    @override
    def conversion_to(self, other_unit: "AngularAccelerationUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: other_unit.from_base_units(self.to_base_units(x)))

    @override
    def from_base_units(self, value_in_base_units: float) -> float:
        return value_in_base_units * self._from_base_multiplier + self._from_base_offset

    @override
    def to_base_units(self, value_in_native_units: float) -> float:
        return value_in_native_units * self._to_base_multiplier + self._to_base_offset

    @override
    def conversion_from_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(x))

    @override
    def conversion_to_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.to_base_units(x))


radians_per_second_squared = AngularAccelerationUnit(None, 1.0, 0.0, 1.0, -0.0, "radian per second squared", "rad/s^2")
rotations_per_second_squared = AngularAccelerationUnit(radians_per_second_squared, 6.283185307179586, 0.0, 0.15915494309189535, -0.0, "rotation per second squared", "R/s^2")
degrees_per_second_squared = AngularAccelerationUnit(radians_per_second_squared, 0.017453292519943295, 0.0, 57.29577951308232, -0.0, "degree per second squared", "°/s^2")
turns_per_second_squared = AngularAccelerationUnit(radians_per_second_squared, 6.283185307179586, 0.0, 0.15915494309189535, -0.0, "turns per second squared", "turns per second squared")

__all__ = ["AngularAccelerationUnit", "radians_per_second_squared", "rotations_per_second_squared", "degrees_per_second_squared", "turns_per_second_squared"]
