# THIS FILE WAS AUTO-GENERATED BY generate_units.py. DO NOT MODIFY

from typing import override

from smartunits import Unit, UnaryFunction
from smartunits.measures.angular_velocity import AngularVelocity



class AngularVelocityUnit(Unit):
    __slots__ = (
        "_to_base_multiplier",
        "_to_base_offset",
        "_from_base_multiplier",
        "_from_base_offset",
    )
    _base_unit: "AngularVelocityUnit"
    _to_base_multiplier: float
    _to_base_offset: float
    _from_base_multiplier: float
    _from_base_offset: float

    def __init__(
        self,
        base_unit: "AngularVelocityUnit",
        to_base_multiplier: float,
        to_base_offset: float,
        from_base_multiplier: float,
        from_base_offset: float,
        name: str,
        symbol: str,
    ) -> None:
        super().__init__(base_unit, name, symbol)
        self._to_base_multiplier = to_base_multiplier
        self._to_base_offset = to_base_offset
        self._from_base_multiplier = from_base_multiplier
        self._from_base_offset = from_base_offset

    @override
    def get_base_unit(self) -> "AngularVelocityUnit":
        return self._base_unit

    @override
    def of(self, magnitude: float):
        return AngularVelocity.of(magnitude, self)

    @override
    def of_base_units(self, magnitude: float):
        return AngularVelocity.of_base_units(magnitude, self)

    @override
    def zero(self):
        return self._zero

    @override
    def one(self):
        return self._one

    @override
    def per(self, other: Unit) -> Unit:
        t = type(other)

        from smartunits import PerUnit
        return PerUnit[AngularVelocityUnit, t].combine(self, other)

    def __mul__(self, other: Unit) -> Unit:
        t = type(other)

        return NotImplemented

    @override
    def convert_from(self, magnitude: float, other_unit: "AngularVelocityUnit") -> float:
        return self.from_base_units(other_unit.to_base_units(magnitude))

    @override
    def convert_to(self, magnitude: float, other_unit: "AngularVelocityUnit") -> float:
        return other_unit.from_base_units(self.to_base_units(magnitude))

    @override
    def conversion_from(self, other_unit: "AngularVelocityUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(other_unit.to_base_units(x)))

    @override
    def conversion_to(self, other_unit: "AngularVelocityUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: other_unit.from_base_units(self.to_base_units(x)))

    @override
    def from_base_units(self, value_in_base_units: float) -> float:
        return value_in_base_units * self._from_base_multiplier + self._from_base_offset

    @override
    def to_base_units(self, value_in_native_units: float) -> float:
        return value_in_native_units * self._to_base_multiplier + self._to_base_offset

    @override
    def conversion_from_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(x))

    @override
    def conversion_to_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.to_base_units(x))


radians_per_second = AngularVelocityUnit(None, 1.0, 0.0, 1.0, -0.0, "radian per second", "rad/s")
revolutions_per_second = AngularVelocityUnit(radians_per_second, 6.283185307179586, 0.0, 0.15915494309189535, -0.0, "revolution per second", "R/s")
rotations_per_second = AngularVelocityUnit(radians_per_second, 6.283185307179586, 0.0, 0.15915494309189535, -0.0, "rotation per second", "R/s")
rotations_per_minute = AngularVelocityUnit(radians_per_second, 0.10471975511965977, 0.0, 9.549296585513721, -0.0, "rotation per minute", "RPM")
degrees_per_second = AngularVelocityUnit(radians_per_second, 0.017453292519943295, 0.0, 57.29577951308232, -0.0, "degree per second", "°/s")
turns_per_second = AngularVelocityUnit(radians_per_second, 6.283185307179586, 0.0, 0.15915494309189535, -0.0, "turns per second", "turns per second")
revolutions_per_minute = AngularVelocityUnit(radians_per_second, 0.10471975511965977, 0.0, 9.549296585513721, -0.0, "revolutions per minute", "revolutions per minute")
milliarcseconds_per_year = AngularVelocityUnit(radians_per_second, 1.5362818500441607e-16, 0.0, 6509222249623367.0, -0.0, "milliarcseconds per year", "milliarcseconds per year")

__all__ = ["AngularVelocityUnit", "radians_per_second", "revolutions_per_second", "rotations_per_second", "rotations_per_minute", "degrees_per_second", "turns_per_second", "revolutions_per_minute", "milliarcseconds_per_year"]
