# THIS FILE WAS AUTO-GENERATED BY generate_units.py. DO NOT MODIFY

from typing import override

from smartunits import Unit, UnaryFunction
from smartunits.measures.angular_momentum import AngularMomentum



class AngularMomentumUnit(Unit):
    __slots__ = (
        "_to_base_multiplier",
        "_to_base_offset",
        "_from_base_multiplier",
        "_from_base_offset",
    )
    _base_unit: "AngularMomentumUnit"
    _to_base_multiplier: float
    _to_base_offset: float
    _from_base_multiplier: float
    _from_base_offset: float

    def __init__(
        self,
        base_unit: "AngularMomentumUnit",
        to_base_multiplier: float,
        to_base_offset: float,
        from_base_multiplier: float,
        from_base_offset: float,
        name: str,
        symbol: str,
    ) -> None:
        super().__init__(base_unit, name, symbol)
        self._to_base_multiplier = to_base_multiplier
        self._to_base_offset = to_base_offset
        self._from_base_multiplier = from_base_multiplier
        self._from_base_offset = from_base_offset

    @override
    def get_base_unit(self) -> "AngularMomentumUnit":
        return self._base_unit

    @override
    def of(self, magnitude: float):
        return AngularMomentum.of(magnitude, self)

    @override
    def of_base_units(self, magnitude: float):
        return AngularMomentum.of_base_units(magnitude, self)

    @override
    def zero(self):
        return self._zero

    @override
    def one(self):
        return self._one

    @override
    def per(self, other: Unit) -> Unit:
        t = type(other)

        from smartunits import PerUnit
        return PerUnit[AngularMomentumUnit, t].combine(self, other)

    def __mul__(self, other: Unit) -> Unit:
        t = type(other)

        return NotImplemented

    @override
    def convert_from(self, magnitude: float, other_unit: "AngularMomentumUnit") -> float:
        return self.from_base_units(other_unit.to_base_units(magnitude))

    @override
    def convert_to(self, magnitude: float, other_unit: "AngularMomentumUnit") -> float:
        return other_unit.from_base_units(self.to_base_units(magnitude))

    @override
    def conversion_from(self, other_unit: "AngularMomentumUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(other_unit.to_base_units(x)))

    @override
    def conversion_to(self, other_unit: "AngularMomentumUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: other_unit.from_base_units(self.to_base_units(x)))

    @override
    def from_base_units(self, value_in_base_units: float) -> float:
        return value_in_base_units * self._from_base_multiplier + self._from_base_offset

    @override
    def to_base_units(self, value_in_native_units: float) -> float:
        return value_in_native_units * self._to_base_multiplier + self._to_base_offset

    @override
    def conversion_from_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(x))

    @override
    def conversion_to_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.to_base_units(x))


kilogram_meters_squared_per_second = AngularMomentumUnit(None, 1.0, 0.0, 1.0, -0.0, "kilogram meter squared per second", "kg m^2/s")
pound_inches_squared_per_second = AngularMomentumUnit(kilogram_meters_squared_per_second, 0.0002926396534292, 0.0, 3417.171898209399, -0.0, "pound inch squared per second", "lb in^2/s")

__all__ = ["AngularMomentumUnit", "kilogram_meters_squared_per_second", "pound_inches_squared_per_second"]
