# THIS FILE WAS AUTO-GENERATED BY generate_units.py. DO NOT MODIFY

from typing import override

from smartunits import Unit, UnaryFunction
from smartunits.measures.area import Area



class AreaUnit(Unit):
    __slots__ = (
        "_to_base_multiplier",
        "_to_base_offset",
        "_from_base_multiplier",
        "_from_base_offset",
    )
    _base_unit: "AreaUnit"
    _to_base_multiplier: float
    _to_base_offset: float
    _from_base_multiplier: float
    _from_base_offset: float

    def __init__(
        self,
        base_unit: "AreaUnit",
        to_base_multiplier: float,
        to_base_offset: float,
        from_base_multiplier: float,
        from_base_offset: float,
        name: str,
        symbol: str,
    ) -> None:
        super().__init__(base_unit, name, symbol)
        self._to_base_multiplier = to_base_multiplier
        self._to_base_offset = to_base_offset
        self._from_base_multiplier = from_base_multiplier
        self._from_base_offset = from_base_offset

    @override
    def get_base_unit(self) -> "AreaUnit":
        return self._base_unit

    @override
    def of(self, magnitude: float):
        return Area.of(magnitude, self)

    @override
    def of_base_units(self, magnitude: float):
        return Area.of_base_units(magnitude, self)

    @override
    def zero(self):
        return self._zero

    @override
    def one(self):
        return self._one

    @override
    def per(self, other: Unit) -> Unit:
        t = type(other)

        from smartunits import PerUnit
        return PerUnit[AreaUnit, t].combine(self, other)

    def __mul__(self, other: Unit) -> Unit:
        t = type(other)

        return NotImplemented

    @override
    def convert_from(self, magnitude: float, other_unit: "AreaUnit") -> float:
        return self.from_base_units(other_unit.to_base_units(magnitude))

    @override
    def convert_to(self, magnitude: float, other_unit: "AreaUnit") -> float:
        return other_unit.from_base_units(self.to_base_units(magnitude))

    @override
    def conversion_from(self, other_unit: "AreaUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(other_unit.to_base_units(x)))

    @override
    def conversion_to(self, other_unit: "AreaUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: other_unit.from_base_units(self.to_base_units(x)))

    @override
    def from_base_units(self, value_in_base_units: float) -> float:
        return value_in_base_units * self._from_base_multiplier + self._from_base_offset

    @override
    def to_base_units(self, value_in_native_units: float) -> float:
        return value_in_native_units * self._to_base_multiplier + self._to_base_offset

    @override
    def conversion_from_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(x))

    @override
    def conversion_to_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.to_base_units(x))


square_meters = AreaUnit(None, 1.0, 0.0, 1.0, -0.0, "square meters", "square meters")
square_feet = AreaUnit(square_meters, 0.09290304, 0.0, 10.763910416709722, -0.0, "square feet", "square feet")
square_inches = AreaUnit(square_meters, 0.00064516, 0.0, 1550.0031000062002, -0.0, "square inches", "square inches")
square_miles = AreaUnit(square_meters, 2589988.110336, 0.0, 3.861021585424458e-07, -0.0, "square miles", "square miles")
square_kilometers = AreaUnit(square_meters, 1000000.0, 0.0, 1e-06, -0.0, "square kilometers", "square kilometers")
hectares = AreaUnit(square_meters, 10000.0, 0.0, 0.0001, -0.0, "hectares", "hectares")
acres = AreaUnit(square_meters, 4046.8564224, 0.0, 0.0002471053814671653, -0.0, "acres", "acres")

__all__ = ["AreaUnit", "square_meters", "square_feet", "square_inches", "square_miles", "square_kilometers", "hectares", "acres"]
