# THIS FILE WAS AUTO-GENERATED BY generate_units.py. DO NOT MODIFY

from typing import override

from smartunits import Unit, UnaryFunction
from smartunits.measures.capacitance import Capacitance



class CapacitanceUnit(Unit):
    __slots__ = (
        "_to_base_multiplier",
        "_to_base_offset",
        "_from_base_multiplier",
        "_from_base_offset",
    )
    _base_unit: "CapacitanceUnit"
    _to_base_multiplier: float
    _to_base_offset: float
    _from_base_multiplier: float
    _from_base_offset: float

    def __init__(
        self,
        base_unit: "CapacitanceUnit",
        to_base_multiplier: float,
        to_base_offset: float,
        from_base_multiplier: float,
        from_base_offset: float,
        name: str,
        symbol: str,
    ) -> None:
        super().__init__(base_unit, name, symbol)
        self._to_base_multiplier = to_base_multiplier
        self._to_base_offset = to_base_offset
        self._from_base_multiplier = from_base_multiplier
        self._from_base_offset = from_base_offset

    @override
    def get_base_unit(self) -> "CapacitanceUnit":
        return self._base_unit

    @override
    def of(self, magnitude: float):
        return Capacitance.of(magnitude, self)

    @override
    def of_base_units(self, magnitude: float):
        return Capacitance.of_base_units(magnitude, self)

    @override
    def zero(self):
        return self._zero

    @override
    def one(self):
        return self._one

    @override
    def per(self, other: Unit) -> Unit:
        t = type(other)

        from smartunits import PerUnit
        return PerUnit[CapacitanceUnit, t].combine(self, other)

    def __mul__(self, other: Unit) -> Unit:
        t = type(other)

        return NotImplemented

    @override
    def convert_from(self, magnitude: float, other_unit: "CapacitanceUnit") -> float:
        return self.from_base_units(other_unit.to_base_units(magnitude))

    @override
    def convert_to(self, magnitude: float, other_unit: "CapacitanceUnit") -> float:
        return other_unit.from_base_units(self.to_base_units(magnitude))

    @override
    def conversion_from(self, other_unit: "CapacitanceUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(other_unit.to_base_units(x)))

    @override
    def conversion_to(self, other_unit: "CapacitanceUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: other_unit.from_base_units(self.to_base_units(x)))

    @override
    def from_base_units(self, value_in_base_units: float) -> float:
        return value_in_base_units * self._from_base_multiplier + self._from_base_offset

    @override
    def to_base_units(self, value_in_native_units: float) -> float:
        return value_in_native_units * self._to_base_multiplier + self._to_base_offset

    @override
    def conversion_from_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(x))

    @override
    def conversion_to_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.to_base_units(x))


farads = CapacitanceUnit(None, 1.0, 0.0, 1.0, -0.0, "farads", "farads")
nanofarads = CapacitanceUnit(farads, 1e-09, 0.0, 999999999.9999999, -0.0, "nanofarads", "nanofarads")
microfarads = CapacitanceUnit(farads, 1e-06, 0.0, 1000000.0, -0.0, "microfarads", "microfarads")
millifarads = CapacitanceUnit(farads, 0.001, 0.0, 1000.0, -0.0, "millifarads", "millifarads")
kilofarads = CapacitanceUnit(farads, 1000.0, 0.0, 0.001, -0.0, "kilofarads", "kilofarads")

__all__ = ["CapacitanceUnit", "farads", "nanofarads", "microfarads", "millifarads", "kilofarads"]
