# THIS FILE WAS AUTO-GENERATED BY generate_units.py. DO NOT MODIFY

from typing import override

from smartunits import Unit, UnaryFunction
from smartunits.measures.charge import Charge



class ChargeUnit(Unit):
    __slots__ = (
        "_to_base_multiplier",
        "_to_base_offset",
        "_from_base_multiplier",
        "_from_base_offset",
    )
    _base_unit: "ChargeUnit"
    _to_base_multiplier: float
    _to_base_offset: float
    _from_base_multiplier: float
    _from_base_offset: float

    def __init__(
        self,
        base_unit: "ChargeUnit",
        to_base_multiplier: float,
        to_base_offset: float,
        from_base_multiplier: float,
        from_base_offset: float,
        name: str,
        symbol: str,
    ) -> None:
        super().__init__(base_unit, name, symbol)
        self._to_base_multiplier = to_base_multiplier
        self._to_base_offset = to_base_offset
        self._from_base_multiplier = from_base_multiplier
        self._from_base_offset = from_base_offset

    @override
    def get_base_unit(self) -> "ChargeUnit":
        return self._base_unit

    @override
    def of(self, magnitude: float):
        return Charge.of(magnitude, self)

    @override
    def of_base_units(self, magnitude: float):
        return Charge.of_base_units(magnitude, self)

    @override
    def zero(self):
        return self._zero

    @override
    def one(self):
        return self._one

    @override
    def per(self, other: Unit) -> Unit:
        t = type(other)

        from smartunits import PerUnit
        return PerUnit[ChargeUnit, t].combine(self, other)

    def __mul__(self, other: Unit) -> Unit:
        t = type(other)

        return NotImplemented

    @override
    def convert_from(self, magnitude: float, other_unit: "ChargeUnit") -> float:
        return self.from_base_units(other_unit.to_base_units(magnitude))

    @override
    def convert_to(self, magnitude: float, other_unit: "ChargeUnit") -> float:
        return other_unit.from_base_units(self.to_base_units(magnitude))

    @override
    def conversion_from(self, other_unit: "ChargeUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(other_unit.to_base_units(x)))

    @override
    def conversion_to(self, other_unit: "ChargeUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: other_unit.from_base_units(self.to_base_units(x)))

    @override
    def from_base_units(self, value_in_base_units: float) -> float:
        return value_in_base_units * self._from_base_multiplier + self._from_base_offset

    @override
    def to_base_units(self, value_in_native_units: float) -> float:
        return value_in_native_units * self._to_base_multiplier + self._to_base_offset

    @override
    def conversion_from_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(x))

    @override
    def conversion_to_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.to_base_units(x))


coulombs = ChargeUnit(None, 1.0, 0.0, 1.0, -0.0, "coulombs", "coulombs")
nanocoulombs = ChargeUnit(coulombs, 1e-09, 0.0, 999999999.9999999, -0.0, "nanocoulombs", "nanocoulombs")
microcoulombs = ChargeUnit(coulombs, 1e-06, 0.0, 1000000.0, -0.0, "microcoulombs", "microcoulombs")
millicoulombs = ChargeUnit(coulombs, 0.001, 0.0, 1000.0, -0.0, "millicoulombs", "millicoulombs")
kilocoulombs = ChargeUnit(coulombs, 1000.0, 0.0, 0.001, -0.0, "kilocoulombs", "kilocoulombs")
ampere_hours = ChargeUnit(coulombs, 3600.0, 0.0, 0.0002777777777777778, -0.0, "ampere hours", "ampere hours")
nanoampere_hours = ChargeUnit(coulombs, 3.6e-06, 0.0, 277777.7777777778, -0.0, "nanoampere hours", "nanoampere hours")
microampere_hours = ChargeUnit(coulombs, 0.0036, 0.0, 277.77777777777777, -0.0, "microampere hours", "microampere hours")
milliampere_hours = ChargeUnit(coulombs, 3.6, 0.0, 0.2777777777777778, -0.0, "milliampere hours", "milliampere hours")
kiloampere_hours = ChargeUnit(coulombs, 3600000.0, 0.0, 2.7777777777777776e-07, -0.0, "kiloampere hours", "kiloampere hours")

__all__ = ["ChargeUnit", "coulombs", "nanocoulombs", "microcoulombs", "millicoulombs", "kilocoulombs", "ampere_hours", "nanoampere_hours", "microampere_hours", "milliampere_hours", "kiloampere_hours"]
