# THIS FILE WAS AUTO-GENERATED BY generate_units.py. DO NOT MODIFY

from typing import override

from smartunits import Unit, UnaryFunction
from smartunits.measures.compound import Compound



class CompoundUnit(Unit):
    __slots__ = (
        "_to_base_multiplier",
        "_to_base_offset",
        "_from_base_multiplier",
        "_from_base_offset",
    )
    _base_unit: "CompoundUnit"
    _to_base_multiplier: float
    _to_base_offset: float
    _from_base_multiplier: float
    _from_base_offset: float

    def __init__(
        self,
        base_unit: "CompoundUnit",
        to_base_multiplier: float,
        to_base_offset: float,
        from_base_multiplier: float,
        from_base_offset: float,
        name: str,
        symbol: str,
    ) -> None:
        super().__init__(base_unit, name, symbol)
        self._to_base_multiplier = to_base_multiplier
        self._to_base_offset = to_base_offset
        self._from_base_multiplier = from_base_multiplier
        self._from_base_offset = from_base_offset

    @override
    def get_base_unit(self) -> "CompoundUnit":
        return self._base_unit

    @override
    def of(self, magnitude: float):
        return Compound.of(magnitude, self)

    @override
    def of_base_units(self, magnitude: float):
        return Compound.of_base_units(magnitude, self)

    @override
    def zero(self):
        return self._zero

    @override
    def one(self):
        return self._one

    @override
    def per(self, other: Unit) -> Unit:
        t = type(other)

        from smartunits import PerUnit
        return PerUnit[CompoundUnit, t].combine(self, other)

    def __mul__(self, other: Unit) -> Unit:
        t = type(other)

        return NotImplemented

    @override
    def convert_from(self, magnitude: float, other_unit: "CompoundUnit") -> float:
        return self.from_base_units(other_unit.to_base_units(magnitude))

    @override
    def convert_to(self, magnitude: float, other_unit: "CompoundUnit") -> float:
        return other_unit.from_base_units(self.to_base_units(magnitude))

    @override
    def conversion_from(self, other_unit: "CompoundUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(other_unit.to_base_units(x)))

    @override
    def conversion_to(self, other_unit: "CompoundUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: other_unit.from_base_units(self.to_base_units(x)))

    @override
    def from_base_units(self, value_in_base_units: float) -> float:
        return value_in_base_units * self._from_base_multiplier + self._from_base_offset

    @override
    def to_base_units(self, value_in_native_units: float) -> float:
        return value_in_native_units * self._to_base_multiplier + self._to_base_offset

    @override
    def conversion_from_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(x))

    @override
    def conversion_to_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.to_base_units(x))


radians_per_meter = CompoundUnit(None, 1.0, 0.0, 1.0, -0.0, "radians per meter", "radians per meter")
radians_per_second_per_volt = CompoundUnit(radians_per_meter, 1.0, 0.0, 1.0, -0.0, "radians per second per volt", "radians per second per volt")
units_per_second = CompoundUnit(radians_per_meter, 1.0, 0.0, 1.0, -0.0, "units per second", "units per second")
units_per_second_squared = CompoundUnit(radians_per_meter, 1.0, 0.0, 1.0, -0.0, "units per second squared", "units per second squared")
volt_seconds = CompoundUnit(radians_per_meter, 1.0, 0.0, 1.0, -0.0, "volt seconds", "volt seconds")
volt_seconds_squared = CompoundUnit(radians_per_meter, 1.0, 0.0, 1.0, -0.0, "volt seconds squared", "volt seconds squared")
volt_seconds_per_meter = CompoundUnit(radians_per_meter, 1.0, 0.0, 1.0, -0.0, "volt seconds per meter", "volt seconds per meter")
volt_seconds_squared_per_meter = CompoundUnit(radians_per_meter, 1.0, 0.0, 1.0, -0.0, "volt seconds squared per meter", "volt seconds squared per meter")
volt_seconds_per_feet = CompoundUnit(radians_per_meter, 3.280839895013123, 0.0, 0.3048, -0.0, "volt seconds per feet", "volt seconds per feet")
volt_seconds_squared_per_feet = CompoundUnit(radians_per_meter, 3.280839895013123, 0.0, 0.3048, -0.0, "volt seconds squared per feet", "volt seconds squared per feet")
volt_seconds_per_radian = CompoundUnit(radians_per_meter, 1.0, 0.0, 1.0, -0.0, "volt seconds per radian", "volt seconds per radian")
volt_seconds_squared_per_radian = CompoundUnit(radians_per_meter, 1.0, 0.0, 1.0, -0.0, "volt seconds squared per radian", "volt seconds squared per radian")
unit_seconds_squared_per_unit = CompoundUnit(radians_per_meter, 1.0, 0.0, 1.0, -0.0, "unit seconds squared per unit", "unit seconds squared per unit")
meters_per_second_squared_per_volt = CompoundUnit(radians_per_meter, 1.0, 0.0, 1.0, -0.0, "meters per second squared per volt", "meters per second squared per volt")
meters_per_second_per_radian = CompoundUnit(radians_per_meter, 1.0, 0.0, 1.0, -0.0, "meters per second per radian", "meters per second per radian")

__all__ = ["CompoundUnit", "radians_per_meter", "radians_per_second_per_volt", "units_per_second", "units_per_second_squared", "volt_seconds", "volt_seconds_squared", "volt_seconds_per_meter", "volt_seconds_squared_per_meter", "volt_seconds_per_feet", "volt_seconds_squared_per_feet", "volt_seconds_per_radian", "volt_seconds_squared_per_radian", "unit_seconds_squared_per_unit", "meters_per_second_squared_per_volt", "meters_per_second_per_radian"]
