# THIS FILE WAS AUTO-GENERATED BY generate_units.py. DO NOT MODIFY

from typing import override

from smartunits import Unit, UnaryFunction
from smartunits.measures.density import Density



class DensityUnit(Unit):
    __slots__ = (
        "_to_base_multiplier",
        "_to_base_offset",
        "_from_base_multiplier",
        "_from_base_offset",
    )
    _base_unit: "DensityUnit"
    _to_base_multiplier: float
    _to_base_offset: float
    _from_base_multiplier: float
    _from_base_offset: float

    def __init__(
        self,
        base_unit: "DensityUnit",
        to_base_multiplier: float,
        to_base_offset: float,
        from_base_multiplier: float,
        from_base_offset: float,
        name: str,
        symbol: str,
    ) -> None:
        super().__init__(base_unit, name, symbol)
        self._to_base_multiplier = to_base_multiplier
        self._to_base_offset = to_base_offset
        self._from_base_multiplier = from_base_multiplier
        self._from_base_offset = from_base_offset

    @override
    def get_base_unit(self) -> "DensityUnit":
        return self._base_unit

    @override
    def of(self, magnitude: float):
        return Density.of(magnitude, self)

    @override
    def of_base_units(self, magnitude: float):
        return Density.of_base_units(magnitude, self)

    @override
    def zero(self):
        return self._zero

    @override
    def one(self):
        return self._one

    @override
    def per(self, other: Unit) -> Unit:
        t = type(other)

        from smartunits import PerUnit
        return PerUnit[DensityUnit, t].combine(self, other)

    def __mul__(self, other: Unit) -> Unit:
        t = type(other)

        return NotImplemented

    @override
    def convert_from(self, magnitude: float, other_unit: "DensityUnit") -> float:
        return self.from_base_units(other_unit.to_base_units(magnitude))

    @override
    def convert_to(self, magnitude: float, other_unit: "DensityUnit") -> float:
        return other_unit.from_base_units(self.to_base_units(magnitude))

    @override
    def conversion_from(self, other_unit: "DensityUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(other_unit.to_base_units(x)))

    @override
    def conversion_to(self, other_unit: "DensityUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: other_unit.from_base_units(self.to_base_units(x)))

    @override
    def from_base_units(self, value_in_base_units: float) -> float:
        return value_in_base_units * self._from_base_multiplier + self._from_base_offset

    @override
    def to_base_units(self, value_in_native_units: float) -> float:
        return value_in_native_units * self._to_base_multiplier + self._to_base_offset

    @override
    def conversion_from_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(x))

    @override
    def conversion_to_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.to_base_units(x))


kilograms_per_cubic_meter = DensityUnit(None, 1.0, 0.0, 1.0, -0.0, "kilograms per cubic meter", "kilograms per cubic meter")
grams_per_milliliter = DensityUnit(kilograms_per_cubic_meter, 1000.0, 0.0, 0.001, -0.0, "grams per milliliter", "grams per milliliter")
kilograms_per_liter = DensityUnit(kilograms_per_cubic_meter, 1000.0, 0.0, 0.001, -0.0, "kilograms per liter", "kilograms per liter")
ounces_per_cubic_foot = DensityUnit(kilograms_per_cubic_meter, 1.0011539608725086, 0.0, 0.9988473692183139, -0.0, "ounces per cubic foot", "ounces per cubic foot")
ounces_per_cubic_inch = DensityUnit(kilograms_per_cubic_meter, 1729.9940443876953, 0.0, 0.0005780366720013389, -0.0, "ounces per cubic inch", "ounces per cubic inch")
ounces_per_gallon = DensityUnit(kilograms_per_cubic_meter, 7.489151707306039, 0.0, 0.13352647123230932, -0.0, "ounces per gallon", "ounces per gallon")
pounds_per_cubic_foot = DensityUnit(kilograms_per_cubic_meter, 16.018463373960138, 0.0, 0.062427960576144616, -0.0, "pounds per cubic foot", "pounds per cubic foot")
pounds_per_cubic_inch = DensityUnit(kilograms_per_cubic_meter, 27679.904710203125, 0.0, 3.612729200008368e-05, -0.0, "pounds per cubic inch", "pounds per cubic inch")
pounds_per_gallon = DensityUnit(kilograms_per_cubic_meter, 119.82642731689663, 0.0, 0.008345404452019332, -0.0, "pounds per gallon", "pounds per gallon")
slugs_per_cubic_foot = DensityUnit(kilograms_per_cubic_meter, 515.3788183929713, 0.0, 0.0019403203319805623, -0.0, "slugs per cubic foot", "slugs per cubic foot")

__all__ = ["DensityUnit", "kilograms_per_cubic_meter", "grams_per_milliliter", "kilograms_per_liter", "ounces_per_cubic_foot", "ounces_per_cubic_inch", "ounces_per_gallon", "pounds_per_cubic_foot", "pounds_per_cubic_inch", "pounds_per_gallon", "slugs_per_cubic_foot"]
