# THIS FILE WAS AUTO-GENERATED BY generate_units.py. DO NOT MODIFY

from typing import override

from smartunits import Unit, UnaryFunction
from smartunits.measures.distance import Distance



class DistanceUnit(Unit):
    __slots__ = (
        "_to_base_multiplier",
        "_to_base_offset",
        "_from_base_multiplier",
        "_from_base_offset",
    )
    _base_unit: "DistanceUnit"
    _to_base_multiplier: float
    _to_base_offset: float
    _from_base_multiplier: float
    _from_base_offset: float

    def __init__(
        self,
        base_unit: "DistanceUnit",
        to_base_multiplier: float,
        to_base_offset: float,
        from_base_multiplier: float,
        from_base_offset: float,
        name: str,
        symbol: str,
    ) -> None:
        super().__init__(base_unit, name, symbol)
        self._to_base_multiplier = to_base_multiplier
        self._to_base_offset = to_base_offset
        self._from_base_multiplier = from_base_multiplier
        self._from_base_offset = from_base_offset

    @override
    def get_base_unit(self) -> "DistanceUnit":
        return self._base_unit

    @override
    def of(self, magnitude: float):
        return Distance.of(magnitude, self)

    @override
    def of_base_units(self, magnitude: float):
        return Distance.of_base_units(magnitude, self)

    @override
    def zero(self):
        return self._zero

    @override
    def one(self):
        return self._one

    @override
    def per(self, other: Unit) -> Unit:
        t = type(other)
        from .time_unit import TimeUnit
        if t is TimeUnit:
            from .linear_velocity_unit import LinearVelocityUnit
            return LinearVelocityUnit.combine(self, other)

        from smartunits import PerUnit
        return PerUnit[DistanceUnit, t].combine(self, other)

    def __mul__(self, other: Unit) -> Unit:
        t = type(other)

        return NotImplemented

    @override
    def convert_from(self, magnitude: float, other_unit: "DistanceUnit") -> float:
        return self.from_base_units(other_unit.to_base_units(magnitude))

    @override
    def convert_to(self, magnitude: float, other_unit: "DistanceUnit") -> float:
        return other_unit.from_base_units(self.to_base_units(magnitude))

    @override
    def conversion_from(self, other_unit: "DistanceUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(other_unit.to_base_units(x)))

    @override
    def conversion_to(self, other_unit: "DistanceUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: other_unit.from_base_units(self.to_base_units(x)))

    @override
    def from_base_units(self, value_in_base_units: float) -> float:
        return value_in_base_units * self._from_base_multiplier + self._from_base_offset

    @override
    def to_base_units(self, value_in_native_units: float) -> float:
        return value_in_native_units * self._to_base_multiplier + self._to_base_offset

    @override
    def conversion_from_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(x))

    @override
    def conversion_to_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.to_base_units(x))


meters = DistanceUnit(None, 1.0, 0.0, 1.0, -0.0, "meter", "m")
millimeters = DistanceUnit(meters, 0.001, 0.0, 1000.0, -0.0, "millimeter", "mm")
centimeters = DistanceUnit(meters, 0.01, 0.0, 100.0, -0.0, "centimeter", "cm")
inches = DistanceUnit(meters, 0.0254, 0.0, 39.37007874015748, -0.0, "inch", "in")
feet = DistanceUnit(meters, 0.3048, 0.0, 3.280839895013123, -0.0, "foot", "ft")
miles = DistanceUnit(meters, 1609.344, 0.0, 0.0006213711922373339, -0.0, "mile", "mi")
nanometers = DistanceUnit(meters, 1e-09, 0.0, 999999999.9999999, -0.0, "nanometers", "nanometers")
micrometers = DistanceUnit(meters, 1e-06, 0.0, 1000000.0, -0.0, "micrometers", "micrometers")
kilometers = DistanceUnit(meters, 1000.0, 0.0, 0.001, -0.0, "kilometers", "kilometers")
mils = DistanceUnit(meters, 2.54e-05, 0.0, 39370.07874015748, -0.0, "mils", "mils")
nautical_miles = DistanceUnit(meters, 1852.0, 0.0, 0.0005399568034557236, -0.0, "nautical miles", "nautical miles")
astronical_units = DistanceUnit(meters, 149597870700.0, 0.0, 6.684587122268445e-12, -0.0, "astronical units", "astronical units")
lightyears = DistanceUnit(meters, 9460730472580800.0, 0.0, 1.0570008340246154e-16, -0.0, "lightyears", "lightyears")
parsecs = DistanceUnit(meters, 3.085677581491367e+16, 0.0, 3.240779289444365e-17, -0.0, "parsecs", "parsecs")
angstroms = DistanceUnit(meters, 1e-10, 0.0, 10000000000.0, -0.0, "angstroms", "angstroms")
cubits = DistanceUnit(meters, 0.4572, 0.0, 2.1872265966754156, -0.0, "cubits", "cubits")
fathoms = DistanceUnit(meters, 1.8288, 0.0, 0.5468066491688539, -0.0, "fathoms", "fathoms")
chains = DistanceUnit(meters, 20.1168, 0.0, 0.049709695378986715, -0.0, "chains", "chains")
furlongs = DistanceUnit(meters, 201.168, 0.0, 0.004970969537898671, -0.0, "furlongs", "furlongs")
hands = DistanceUnit(meters, 0.1016, 0.0, 9.84251968503937, -0.0, "hands", "hands")
leagues = DistanceUnit(meters, 4828.032, 0.0, 0.000207123730745778, -0.0, "leagues", "leagues")
nautical_leagues = DistanceUnit(meters, 5556.0, 0.0, 0.00017998560115190784, -0.0, "nautical leagues", "nautical leagues")
yards = DistanceUnit(meters, 0.9144, 0.0, 1.0936132983377078, -0.0, "yards", "yards")

__all__ = ["DistanceUnit", "meters", "millimeters", "centimeters", "inches", "feet", "miles", "nanometers", "micrometers", "kilometers", "mils", "nautical_miles", "astronical_units", "lightyears", "parsecs", "angstroms", "cubits", "fathoms", "chains", "furlongs", "hands", "leagues", "nautical_leagues", "yards"]
