# THIS FILE WAS AUTO-GENERATED BY generate_units.py. DO NOT MODIFY

from typing import override

from smartunits import Unit, UnaryFunction
from smartunits.measures.energy import Energy



class EnergyUnit(Unit):
    __slots__ = (
        "_to_base_multiplier",
        "_to_base_offset",
        "_from_base_multiplier",
        "_from_base_offset",
    )
    _base_unit: "EnergyUnit"
    _to_base_multiplier: float
    _to_base_offset: float
    _from_base_multiplier: float
    _from_base_offset: float

    def __init__(
        self,
        base_unit: "EnergyUnit",
        to_base_multiplier: float,
        to_base_offset: float,
        from_base_multiplier: float,
        from_base_offset: float,
        name: str,
        symbol: str,
    ) -> None:
        super().__init__(base_unit, name, symbol)
        self._to_base_multiplier = to_base_multiplier
        self._to_base_offset = to_base_offset
        self._from_base_multiplier = from_base_multiplier
        self._from_base_offset = from_base_offset

    @override
    def get_base_unit(self) -> "EnergyUnit":
        return self._base_unit

    @override
    def of(self, magnitude: float):
        return Energy.of(magnitude, self)

    @override
    def of_base_units(self, magnitude: float):
        return Energy.of_base_units(magnitude, self)

    @override
    def zero(self):
        return self._zero

    @override
    def one(self):
        return self._one

    @override
    def per(self, other: Unit) -> Unit:
        t = type(other)
        from .time_unit import TimeUnit
        if t is TimeUnit:
            from .power_unit import PowerUnit
            return PowerUnit.combine(self, other)

        from smartunits import PerUnit
        return PerUnit[EnergyUnit, t].combine(self, other)

    def __mul__(self, other: Unit) -> Unit:
        t = type(other)

        return NotImplemented

    @override
    def convert_from(self, magnitude: float, other_unit: "EnergyUnit") -> float:
        return self.from_base_units(other_unit.to_base_units(magnitude))

    @override
    def convert_to(self, magnitude: float, other_unit: "EnergyUnit") -> float:
        return other_unit.from_base_units(self.to_base_units(magnitude))

    @override
    def conversion_from(self, other_unit: "EnergyUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(other_unit.to_base_units(x)))

    @override
    def conversion_to(self, other_unit: "EnergyUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: other_unit.from_base_units(self.to_base_units(x)))

    @override
    def from_base_units(self, value_in_base_units: float) -> float:
        return value_in_base_units * self._from_base_multiplier + self._from_base_offset

    @override
    def to_base_units(self, value_in_native_units: float) -> float:
        return value_in_native_units * self._to_base_multiplier + self._to_base_offset

    @override
    def conversion_from_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(x))

    @override
    def conversion_to_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.to_base_units(x))


joules = EnergyUnit(None, 1.0, 0.0, 1.0, -0.0, "joule", "J")
millijoules = EnergyUnit(joules, 0.001, 0.0, 1000.0, -0.0, "millijoule", "mJ")
kilojoules = EnergyUnit(joules, 1000.0, 0.0, 0.001, -0.0, "kilojoule", "kJ")
nanojoules = EnergyUnit(joules, 1e-09, 0.0, 999999999.9999999, -0.0, "nanojoules", "nanojoules")
microjoules = EnergyUnit(joules, 1e-06, 0.0, 1000000.0, -0.0, "microjoules", "microjoules")
calories = EnergyUnit(joules, 4.184, 0.0, 0.2390057361376673, -0.0, "calories", "calories")
nanocalories = EnergyUnit(joules, 4.184e-09, 0.0, 239005736.13766733, -0.0, "nanocalories", "nanocalories")
microcalories = EnergyUnit(joules, 4.184e-06, 0.0, 239005.7361376673, -0.0, "microcalories", "microcalories")
millicalories = EnergyUnit(joules, 0.004184, 0.0, 239.0057361376673, -0.0, "millicalories", "millicalories")
kilocalories = EnergyUnit(joules, 4184.0, 0.0, 0.0002390057361376673, -0.0, "kilocalories", "kilocalories")
kilowatt_hours = EnergyUnit(joules, 3600000.0, 0.0, 2.7777777777777776e-07, -0.0, "kilowatt hours", "kilowatt hours")
watt_hours = EnergyUnit(joules, 3600.0, 0.0, 0.0002777777777777778, -0.0, "watt hours", "watt hours")
british_thermal_units = EnergyUnit(joules, 1055.05585262, 0.0, 0.0009478171203133172, -0.0, "british thermal units", "british thermal units")
british_thermal_units_iso = EnergyUnit(joules, 1055.06, 0.0, 0.0009478133944988911, -0.0, "british thermal units iso", "british thermal units iso")
british_thermal_units_59 = EnergyUnit(joules, 1054.804, 0.0, 0.0009480434279733486, -0.0, "british thermal units 59", "british thermal units 59")
therms = EnergyUnit(joules, 105505585.262, 0.0, 9.478171203133172e-09, -0.0, "therms", "therms")
foot_pounds = EnergyUnit(joules, 1.3558179483314003, 0.0, 0.7375621492772654, -0.0, "foot pounds", "foot pounds")

__all__ = ["EnergyUnit", "joules", "millijoules", "kilojoules", "nanojoules", "microjoules", "calories", "nanocalories", "microcalories", "millicalories", "kilocalories", "kilowatt_hours", "watt_hours", "british_thermal_units", "british_thermal_units_iso", "british_thermal_units_59", "therms", "foot_pounds"]
