# THIS FILE WAS AUTO-GENERATED BY generate_units.py. DO NOT MODIFY

from typing import override

from smartunits import Unit, UnaryFunction
from smartunits.measures.force import Force



class ForceUnit(Unit):
    __slots__ = (
        "_to_base_multiplier",
        "_to_base_offset",
        "_from_base_multiplier",
        "_from_base_offset",
    )
    _base_unit: "ForceUnit"
    _to_base_multiplier: float
    _to_base_offset: float
    _from_base_multiplier: float
    _from_base_offset: float

    def __init__(
        self,
        base_unit: "ForceUnit",
        to_base_multiplier: float,
        to_base_offset: float,
        from_base_multiplier: float,
        from_base_offset: float,
        name: str,
        symbol: str,
    ) -> None:
        super().__init__(base_unit, name, symbol)
        self._to_base_multiplier = to_base_multiplier
        self._to_base_offset = to_base_offset
        self._from_base_multiplier = from_base_multiplier
        self._from_base_offset = from_base_offset

    @override
    def get_base_unit(self) -> "ForceUnit":
        return self._base_unit

    @override
    def of(self, magnitude: float):
        return Force.of(magnitude, self)

    @override
    def of_base_units(self, magnitude: float):
        return Force.of_base_units(magnitude, self)

    @override
    def zero(self):
        return self._zero

    @override
    def one(self):
        return self._one

    @override
    def per(self, other: Unit) -> Unit:
        t = type(other)
        from .mass_unit import MassUnit
        if t is MassUnit:
            from .linear_acceleration_unit import LinearAccelerationUnit
            return LinearAccelerationUnit.combine(self, other)
        from .linear_acceleration_unit import LinearAccelerationUnit
        if t is LinearAccelerationUnit:
            from .mass_unit import MassUnit
            return MassUnit.combine(self, other)

        from smartunits import PerUnit
        return PerUnit[ForceUnit, t].combine(self, other)

    def __mul__(self, other: Unit) -> Unit:
        t = type(other)

        return NotImplemented

    @override
    def convert_from(self, magnitude: float, other_unit: "ForceUnit") -> float:
        return self.from_base_units(other_unit.to_base_units(magnitude))

    @override
    def convert_to(self, magnitude: float, other_unit: "ForceUnit") -> float:
        return other_unit.from_base_units(self.to_base_units(magnitude))

    @override
    def conversion_from(self, other_unit: "ForceUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(other_unit.to_base_units(x)))

    @override
    def conversion_to(self, other_unit: "ForceUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: other_unit.from_base_units(self.to_base_units(x)))

    @override
    def from_base_units(self, value_in_base_units: float) -> float:
        return value_in_base_units * self._from_base_multiplier + self._from_base_offset

    @override
    def to_base_units(self, value_in_native_units: float) -> float:
        return value_in_native_units * self._to_base_multiplier + self._to_base_offset

    @override
    def conversion_from_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(x))

    @override
    def conversion_to_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.to_base_units(x))


newtons = ForceUnit(None, 1.0, 0.0, 1.0, -0.0, "newton", "N")
pounds_force = ForceUnit(newtons, 4.4482216152605, 0.0, 0.2248089430997105, -0.0, "pound-force", "lbsf.")
ounces_force = ForceUnit(newtons, 0.2780138509537812, 0.0, 3.596943089595368, -0.0, "ounce-force", "ozf")
nanonewtons = ForceUnit(newtons, 1e-09, 0.0, 999999999.9999999, -0.0, "nanonewtons", "nanonewtons")
micronewtons = ForceUnit(newtons, 1e-06, 0.0, 1000000.0, -0.0, "micronewtons", "micronewtons")
millinewtons = ForceUnit(newtons, 0.001, 0.0, 1000.0, -0.0, "millinewtons", "millinewtons")
kilonewtons = ForceUnit(newtons, 1000.0, 0.0, 0.001, -0.0, "kilonewtons", "kilonewtons")
pounds = ForceUnit(newtons, 4.4482216152605, 0.0, 0.2248089430997105, -0.0, "pounds", "pounds")
dynes = ForceUnit(newtons, 1e-05, 0.0, 99999.99999999999, -0.0, "dynes", "dynes")
kiloponds = ForceUnit(newtons, 9.80665, 0.0, 0.10197162129779283, -0.0, "kiloponds", "kiloponds")
poundals = ForceUnit(newtons, 0.138254954376, 0.0, 7.233013851209894, -0.0, "poundals", "poundals")

__all__ = ["ForceUnit", "newtons", "pounds_force", "ounces_force", "nanonewtons", "micronewtons", "millinewtons", "kilonewtons", "pounds", "dynes", "kiloponds", "poundals"]
