# THIS FILE WAS AUTO-GENERATED BY generate_units.py. DO NOT MODIFY

from typing import override

from smartunits import Unit, UnaryFunction
from smartunits.measures.illuminance import Illuminance



class IlluminanceUnit(Unit):
    __slots__ = (
        "_to_base_multiplier",
        "_to_base_offset",
        "_from_base_multiplier",
        "_from_base_offset",
    )
    _base_unit: "IlluminanceUnit"
    _to_base_multiplier: float
    _to_base_offset: float
    _from_base_multiplier: float
    _from_base_offset: float

    def __init__(
        self,
        base_unit: "IlluminanceUnit",
        to_base_multiplier: float,
        to_base_offset: float,
        from_base_multiplier: float,
        from_base_offset: float,
        name: str,
        symbol: str,
    ) -> None:
        super().__init__(base_unit, name, symbol)
        self._to_base_multiplier = to_base_multiplier
        self._to_base_offset = to_base_offset
        self._from_base_multiplier = from_base_multiplier
        self._from_base_offset = from_base_offset

    @override
    def get_base_unit(self) -> "IlluminanceUnit":
        return self._base_unit

    @override
    def of(self, magnitude: float):
        return Illuminance.of(magnitude, self)

    @override
    def of_base_units(self, magnitude: float):
        return Illuminance.of_base_units(magnitude, self)

    @override
    def zero(self):
        return self._zero

    @override
    def one(self):
        return self._one

    @override
    def per(self, other: Unit) -> Unit:
        t = type(other)

        from smartunits import PerUnit
        return PerUnit[IlluminanceUnit, t].combine(self, other)

    def __mul__(self, other: Unit) -> Unit:
        t = type(other)

        return NotImplemented

    @override
    def convert_from(self, magnitude: float, other_unit: "IlluminanceUnit") -> float:
        return self.from_base_units(other_unit.to_base_units(magnitude))

    @override
    def convert_to(self, magnitude: float, other_unit: "IlluminanceUnit") -> float:
        return other_unit.from_base_units(self.to_base_units(magnitude))

    @override
    def conversion_from(self, other_unit: "IlluminanceUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(other_unit.to_base_units(x)))

    @override
    def conversion_to(self, other_unit: "IlluminanceUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: other_unit.from_base_units(self.to_base_units(x)))

    @override
    def from_base_units(self, value_in_base_units: float) -> float:
        return value_in_base_units * self._from_base_multiplier + self._from_base_offset

    @override
    def to_base_units(self, value_in_native_units: float) -> float:
        return value_in_native_units * self._to_base_multiplier + self._to_base_offset

    @override
    def conversion_from_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(x))

    @override
    def conversion_to_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.to_base_units(x))


luxes = IlluminanceUnit(None, 1, 0.0, 1.0, -0.0, "luxes", "luxes")
nanoluxes = IlluminanceUnit(luxes, 1e-09, 0.0, 999999999.9999999, -0.0, "nanoluxes", "nanoluxes")
microluxes = IlluminanceUnit(luxes, 1e-06, 0.0, 1000000.0, -0.0, "microluxes", "microluxes")
milliluxes = IlluminanceUnit(luxes, 0.001, 0.0, 1000.0, -0.0, "milliluxes", "milliluxes")
kiloluxes = IlluminanceUnit(luxes, 1000.0, 0.0, 0.001, -0.0, "kiloluxes", "kiloluxes")
footcandles = IlluminanceUnit(luxes, 10.763910416709722, 0.0, 0.09290304, -0.0, "footcandles", "footcandles")
lumens_per_square_inch = IlluminanceUnit(luxes, 1550.0031000062, 0.0, 0.00064516, -0.0, "lumens per square inch", "lumens per square inch")
phots = IlluminanceUnit(luxes, 10000.0, 0.0, 0.0001, -0.0, "phots", "phots")

__all__ = ["IlluminanceUnit", "luxes", "nanoluxes", "microluxes", "milliluxes", "kiloluxes", "footcandles", "lumens_per_square_inch", "phots"]
