# THIS FILE WAS AUTO-GENERATED BY generate_units.py. DO NOT MODIFY

from typing import override

from smartunits import Unit, UnaryFunction
from smartunits.measures.linear_velocity import LinearVelocity



class LinearVelocityUnit(Unit):
    __slots__ = (
        "_to_base_multiplier",
        "_to_base_offset",
        "_from_base_multiplier",
        "_from_base_offset",
    )
    _base_unit: "LinearVelocityUnit"
    _to_base_multiplier: float
    _to_base_offset: float
    _from_base_multiplier: float
    _from_base_offset: float

    def __init__(
        self,
        base_unit: "LinearVelocityUnit",
        to_base_multiplier: float,
        to_base_offset: float,
        from_base_multiplier: float,
        from_base_offset: float,
        name: str,
        symbol: str,
    ) -> None:
        super().__init__(base_unit, name, symbol)
        self._to_base_multiplier = to_base_multiplier
        self._to_base_offset = to_base_offset
        self._from_base_multiplier = from_base_multiplier
        self._from_base_offset = from_base_offset

    @override
    def get_base_unit(self) -> "LinearVelocityUnit":
        return self._base_unit

    @override
    def of(self, magnitude: float):
        return LinearVelocity.of(magnitude, self)

    @override
    def of_base_units(self, magnitude: float):
        return LinearVelocity.of_base_units(magnitude, self)

    @override
    def zero(self):
        return self._zero

    @override
    def one(self):
        return self._one

    @override
    def per(self, other: Unit) -> Unit:
        t = type(other)
        from .time_unit import TimeUnit
        if t is TimeUnit:
            from .distance_unit import DistanceUnit
            return DistanceUnit.combine(self, other)
        from .frequency_unit import FrequencyUnit
        if t is FrequencyUnit:
            from .linear_acceleration_unit import LinearAccelerationUnit
            return LinearAccelerationUnit.combine(self, other)

        from smartunits import PerUnit
        return PerUnit[LinearVelocityUnit, t].combine(self, other)

    def __mul__(self, other: Unit) -> Unit:
        t = type(other)

        return NotImplemented

    @override
    def convert_from(self, magnitude: float, other_unit: "LinearVelocityUnit") -> float:
        return self.from_base_units(other_unit.to_base_units(magnitude))

    @override
    def convert_to(self, magnitude: float, other_unit: "LinearVelocityUnit") -> float:
        return other_unit.from_base_units(self.to_base_units(magnitude))

    @override
    def conversion_from(self, other_unit: "LinearVelocityUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(other_unit.to_base_units(x)))

    @override
    def conversion_to(self, other_unit: "LinearVelocityUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: other_unit.from_base_units(self.to_base_units(x)))

    @override
    def from_base_units(self, value_in_base_units: float) -> float:
        return value_in_base_units * self._from_base_multiplier + self._from_base_offset

    @override
    def to_base_units(self, value_in_native_units: float) -> float:
        return value_in_native_units * self._to_base_multiplier + self._to_base_offset

    @override
    def conversion_from_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(x))

    @override
    def conversion_to_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.to_base_units(x))


meters_per_second = LinearVelocityUnit(None, 1.0, 0.0, 1.0, -0.0, "meter per second", "m/s")
feet_per_second = LinearVelocityUnit(meters_per_second, 0.3048, 0.0, 3.280839895013123, -0.0, "foot per second", "ft/s")
inches_per_second = LinearVelocityUnit(meters_per_second, 0.0254, 0.0, 39.37007874015748, -0.0, "inch per second", "in/s")

__all__ = ["LinearVelocityUnit", "meters_per_second", "feet_per_second", "inches_per_second"]
