# THIS FILE WAS AUTO-GENERATED BY generate_units.py. DO NOT MODIFY

from typing import override

from smartunits import Unit, UnaryFunction
from smartunits.measures.linear_acceleration import LinearAcceleration



class LinearAccelerationUnit(Unit):
    __slots__ = (
        "_to_base_multiplier",
        "_to_base_offset",
        "_from_base_multiplier",
        "_from_base_offset",
    )
    _base_unit: "LinearAccelerationUnit"
    _to_base_multiplier: float
    _to_base_offset: float
    _from_base_multiplier: float
    _from_base_offset: float

    def __init__(
        self,
        base_unit: "LinearAccelerationUnit",
        to_base_multiplier: float,
        to_base_offset: float,
        from_base_multiplier: float,
        from_base_offset: float,
        name: str,
        symbol: str,
    ) -> None:
        super().__init__(base_unit, name, symbol)
        self._to_base_multiplier = to_base_multiplier
        self._to_base_offset = to_base_offset
        self._from_base_multiplier = from_base_multiplier
        self._from_base_offset = from_base_offset

    @override
    def get_base_unit(self) -> "LinearAccelerationUnit":
        return self._base_unit

    @override
    def of(self, magnitude: float):
        return LinearAcceleration.of(magnitude, self)

    @override
    def of_base_units(self, magnitude: float):
        return LinearAcceleration.of_base_units(magnitude, self)

    @override
    def zero(self):
        return self._zero

    @override
    def one(self):
        return self._one

    @override
    def per(self, other: Unit) -> Unit:
        t = type(other)
        from .time_unit import TimeUnit
        if t is TimeUnit:
            from .linear_velocity_unit import LinearVelocityUnit
            return LinearVelocityUnit.combine(self, other)

        from smartunits import PerUnit
        return PerUnit[LinearAccelerationUnit, t].combine(self, other)

    def __mul__(self, other: Unit) -> Unit:
        t = type(other)

        return NotImplemented

    @override
    def convert_from(self, magnitude: float, other_unit: "LinearAccelerationUnit") -> float:
        return self.from_base_units(other_unit.to_base_units(magnitude))

    @override
    def convert_to(self, magnitude: float, other_unit: "LinearAccelerationUnit") -> float:
        return other_unit.from_base_units(self.to_base_units(magnitude))

    @override
    def conversion_from(self, other_unit: "LinearAccelerationUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(other_unit.to_base_units(x)))

    @override
    def conversion_to(self, other_unit: "LinearAccelerationUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: other_unit.from_base_units(self.to_base_units(x)))

    @override
    def from_base_units(self, value_in_base_units: float) -> float:
        return value_in_base_units * self._from_base_multiplier + self._from_base_offset

    @override
    def to_base_units(self, value_in_native_units: float) -> float:
        return value_in_native_units * self._to_base_multiplier + self._to_base_offset

    @override
    def conversion_from_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(x))

    @override
    def conversion_to_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.to_base_units(x))


meters_per_second_squared = LinearAccelerationUnit(None, 1.0, 0.0, 1.0, -0.0, "meter per second squared", "m/s^2")
feet_per_second_squared = LinearAccelerationUnit(meters_per_second_squared, 0.3048, 0.0, 3.280839895013123, -0.0, "foot per second squared", "ft/s^2")
inches_per_second_squared = LinearAccelerationUnit(meters_per_second_squared, 0.0254, 0.0, 39.37007874015748, -0.0, "inch per second squared", "in/s^2")
gs = LinearAccelerationUnit(meters_per_second_squared, 9.80665, 0.0, 0.10197162129779283, -0.0, "G", "G")

__all__ = ["LinearAccelerationUnit", "meters_per_second_squared", "feet_per_second_squared", "inches_per_second_squared", "gs"]
