# THIS FILE WAS AUTO-GENERATED BY generate_units.py. DO NOT MODIFY

from typing import override

from smartunits import Unit, UnaryFunction
from smartunits.measures.mass import Mass



class MassUnit(Unit):
    __slots__ = (
        "_to_base_multiplier",
        "_to_base_offset",
        "_from_base_multiplier",
        "_from_base_offset",
    )
    _base_unit: "MassUnit"
    _to_base_multiplier: float
    _to_base_offset: float
    _from_base_multiplier: float
    _from_base_offset: float

    def __init__(
        self,
        base_unit: "MassUnit",
        to_base_multiplier: float,
        to_base_offset: float,
        from_base_multiplier: float,
        from_base_offset: float,
        name: str,
        symbol: str,
    ) -> None:
        super().__init__(base_unit, name, symbol)
        self._to_base_multiplier = to_base_multiplier
        self._to_base_offset = to_base_offset
        self._from_base_multiplier = from_base_multiplier
        self._from_base_offset = from_base_offset

    @override
    def get_base_unit(self) -> "MassUnit":
        return self._base_unit

    @override
    def of(self, magnitude: float):
        return Mass.of(magnitude, self)

    @override
    def of_base_units(self, magnitude: float):
        return Mass.of_base_units(magnitude, self)

    @override
    def zero(self):
        return self._zero

    @override
    def one(self):
        return self._one

    @override
    def per(self, other: Unit) -> Unit:
        t = type(other)
        from .linear_acceleration_unit import LinearAccelerationUnit
        if t is LinearAccelerationUnit:
            from .force_unit import ForceUnit
            return ForceUnit.combine(self, other)

        from smartunits import PerUnit
        return PerUnit[MassUnit, t].combine(self, other)

    def __mul__(self, other: Unit) -> Unit:
        t = type(other)

        return NotImplemented

    @override
    def convert_from(self, magnitude: float, other_unit: "MassUnit") -> float:
        return self.from_base_units(other_unit.to_base_units(magnitude))

    @override
    def convert_to(self, magnitude: float, other_unit: "MassUnit") -> float:
        return other_unit.from_base_units(self.to_base_units(magnitude))

    @override
    def conversion_from(self, other_unit: "MassUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(other_unit.to_base_units(x)))

    @override
    def conversion_to(self, other_unit: "MassUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: other_unit.from_base_units(self.to_base_units(x)))

    @override
    def from_base_units(self, value_in_base_units: float) -> float:
        return value_in_base_units * self._from_base_multiplier + self._from_base_offset

    @override
    def to_base_units(self, value_in_native_units: float) -> float:
        return value_in_native_units * self._to_base_multiplier + self._to_base_offset

    @override
    def conversion_from_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(x))

    @override
    def conversion_to_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.to_base_units(x))


kilograms = MassUnit(None, 1.0, 0.0, 1.0, -0.0, "kilogram", "kg")
grams = MassUnit(kilograms, 0.001, 0.0, 1000.0, -0.0, "gram", "g")
pounds = MassUnit(kilograms, 0.45359237, 0.0, 2.2046226218487757, -0.0, "pound", "lb.")
ounces = MassUnit(kilograms, 0.028349523125, 0.0, 35.27396194958041, -0.0, "ounce", "oz.")
nanograms = MassUnit(kilograms, 1e-12, 0.0, 1000000000000.0, -0.0, "nanograms", "nanograms")
micrograms = MassUnit(kilograms, 1e-09, 0.0, 999999999.9999999, -0.0, "micrograms", "micrograms")
milligrams = MassUnit(kilograms, 1e-06, 0.0, 1000000.0, -0.0, "milligrams", "milligrams")
metric_tons = MassUnit(kilograms, 1000.0, 0.0, 0.001, -0.0, "metric tons", "metric tons")
long_tons = MassUnit(kilograms, 1016.0469088, 0.0, 0.0009842065276110606, -0.0, "long tons", "long tons")
short_tons = MassUnit(kilograms, 907.18474, 0.0, 0.001102311310924388, -0.0, "short tons", "short tons")
stone = MassUnit(kilograms, 6.35029318, 0.0, 0.1574730444177697, -0.0, "stone", "stone")
carats = MassUnit(kilograms, 0.0002, 0.0, 5000.0, -0.0, "carats", "carats")
slugs = MassUnit(kilograms, 14.5939029372, 0.0, 0.06852176585682164, -0.0, "slugs", "slugs")

__all__ = ["MassUnit", "kilograms", "grams", "pounds", "ounces", "nanograms", "micrograms", "milligrams", "metric_tons", "long_tons", "short_tons", "stone", "carats", "slugs"]
