# THIS FILE WAS AUTO-GENERATED BY generate_units.py. DO NOT MODIFY

from typing import override

from smartunits import Unit, UnaryFunction
from smartunits.measures.pressure import Pressure



class PressureUnit(Unit):
    __slots__ = (
        "_to_base_multiplier",
        "_to_base_offset",
        "_from_base_multiplier",
        "_from_base_offset",
    )
    _base_unit: "PressureUnit"
    _to_base_multiplier: float
    _to_base_offset: float
    _from_base_multiplier: float
    _from_base_offset: float

    def __init__(
        self,
        base_unit: "PressureUnit",
        to_base_multiplier: float,
        to_base_offset: float,
        from_base_multiplier: float,
        from_base_offset: float,
        name: str,
        symbol: str,
    ) -> None:
        super().__init__(base_unit, name, symbol)
        self._to_base_multiplier = to_base_multiplier
        self._to_base_offset = to_base_offset
        self._from_base_multiplier = from_base_multiplier
        self._from_base_offset = from_base_offset

    @override
    def get_base_unit(self) -> "PressureUnit":
        return self._base_unit

    @override
    def of(self, magnitude: float):
        return Pressure.of(magnitude, self)

    @override
    def of_base_units(self, magnitude: float):
        return Pressure.of_base_units(magnitude, self)

    @override
    def zero(self):
        return self._zero

    @override
    def one(self):
        return self._one

    @override
    def per(self, other: Unit) -> Unit:
        t = type(other)

        from smartunits import PerUnit
        return PerUnit[PressureUnit, t].combine(self, other)

    def __mul__(self, other: Unit) -> Unit:
        t = type(other)

        return NotImplemented

    @override
    def convert_from(self, magnitude: float, other_unit: "PressureUnit") -> float:
        return self.from_base_units(other_unit.to_base_units(magnitude))

    @override
    def convert_to(self, magnitude: float, other_unit: "PressureUnit") -> float:
        return other_unit.from_base_units(self.to_base_units(magnitude))

    @override
    def conversion_from(self, other_unit: "PressureUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(other_unit.to_base_units(x)))

    @override
    def conversion_to(self, other_unit: "PressureUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: other_unit.from_base_units(self.to_base_units(x)))

    @override
    def from_base_units(self, value_in_base_units: float) -> float:
        return value_in_base_units * self._from_base_multiplier + self._from_base_offset

    @override
    def to_base_units(self, value_in_native_units: float) -> float:
        return value_in_native_units * self._to_base_multiplier + self._to_base_offset

    @override
    def conversion_from_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(x))

    @override
    def conversion_to_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.to_base_units(x))


pascals = PressureUnit(None, 1.0, 0.0, 1.0, -0.0, "pascals", "pascals")
nanopascals = PressureUnit(pascals, 1e-09, 0.0, 999999999.9999999, -0.0, "nanopascals", "nanopascals")
micropascals = PressureUnit(pascals, 1e-06, 0.0, 1000000.0, -0.0, "micropascals", "micropascals")
millipascals = PressureUnit(pascals, 0.001, 0.0, 1000.0, -0.0, "millipascals", "millipascals")
kilopascals = PressureUnit(pascals, 1000.0, 0.0, 0.001, -0.0, "kilopascals", "kilopascals")
bars = PressureUnit(pascals, 100000.0, 0.0, 1e-05, -0.0, "bars", "bars")
mbars = PressureUnit(pascals, 100.0, 0.0, 0.01, -0.0, "mbars", "mbars")
atmospheres = PressureUnit(pascals, 101325.0, 0.0, 9.869232667160129e-06, -0.0, "atmospheres", "atmospheres")
pounds_per_square_inch = PressureUnit(pascals, 6894.757293168, 0.0, 0.00014503773773021683, -0.0, "pounds per square inch", "pounds per square inch")
torrs = PressureUnit(pascals, 133.32236842105263, 0.0, 0.007500616827041697, -0.0, "torrs", "torrs")

__all__ = ["PressureUnit", "pascals", "nanopascals", "micropascals", "millipascals", "kilopascals", "bars", "mbars", "atmospheres", "pounds_per_square_inch", "torrs"]
