# THIS FILE WAS AUTO-GENERATED BY generate_units.py. DO NOT MODIFY

from typing import override

from smartunits import Unit, UnaryFunction
from smartunits.measures.resistance import Resistance



class ResistanceUnit(Unit):
    __slots__ = (
        "_to_base_multiplier",
        "_to_base_offset",
        "_from_base_multiplier",
        "_from_base_offset",
    )
    _base_unit: "ResistanceUnit"
    _to_base_multiplier: float
    _to_base_offset: float
    _from_base_multiplier: float
    _from_base_offset: float

    def __init__(
        self,
        base_unit: "ResistanceUnit",
        to_base_multiplier: float,
        to_base_offset: float,
        from_base_multiplier: float,
        from_base_offset: float,
        name: str,
        symbol: str,
    ) -> None:
        super().__init__(base_unit, name, symbol)
        self._to_base_multiplier = to_base_multiplier
        self._to_base_offset = to_base_offset
        self._from_base_multiplier = from_base_multiplier
        self._from_base_offset = from_base_offset

    @override
    def get_base_unit(self) -> "ResistanceUnit":
        return self._base_unit

    @override
    def of(self, magnitude: float):
        return Resistance.of(magnitude, self)

    @override
    def of_base_units(self, magnitude: float):
        return Resistance.of_base_units(magnitude, self)

    @override
    def zero(self):
        return self._zero

    @override
    def one(self):
        return self._one

    @override
    def per(self, other: Unit) -> Unit:
        t = type(other)
        from .current_unit import CurrentUnit
        if t is CurrentUnit:
            from .voltage_unit import VoltageUnit
            return VoltageUnit.combine(self, other)

        from smartunits import PerUnit
        return PerUnit[ResistanceUnit, t].combine(self, other)

    def __mul__(self, other: Unit) -> Unit:
        t = type(other)

        return NotImplemented

    @override
    def convert_from(self, magnitude: float, other_unit: "ResistanceUnit") -> float:
        return self.from_base_units(other_unit.to_base_units(magnitude))

    @override
    def convert_to(self, magnitude: float, other_unit: "ResistanceUnit") -> float:
        return other_unit.from_base_units(self.to_base_units(magnitude))

    @override
    def conversion_from(self, other_unit: "ResistanceUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(other_unit.to_base_units(x)))

    @override
    def conversion_to(self, other_unit: "ResistanceUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: other_unit.from_base_units(self.to_base_units(x)))

    @override
    def from_base_units(self, value_in_base_units: float) -> float:
        return value_in_base_units * self._from_base_multiplier + self._from_base_offset

    @override
    def to_base_units(self, value_in_native_units: float) -> float:
        return value_in_native_units * self._to_base_multiplier + self._to_base_offset

    @override
    def conversion_from_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(x))

    @override
    def conversion_to_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.to_base_units(x))


ohms = ResistanceUnit(None, 1.0, 0.0, 1.0, -0.0, "ohm", "Ω")
kilo_ohms = ResistanceUnit(ohms, 1000.0, 0.0, 0.001, -0.0, "kiloohm", "kΩ")
milli_ohms = ResistanceUnit(ohms, 0.001, 0.0, 1000.0, -0.0, "milliohm", "mΩ")
nanoohms = ResistanceUnit(ohms, 1e-09, 0.0, 999999999.9999999, -0.0, "nanoohms", "nanoohms")
microohms = ResistanceUnit(ohms, 1e-06, 0.0, 1000000.0, -0.0, "microohms", "microohms")
milliohms = ResistanceUnit(ohms, 0.001, 0.0, 1000.0, -0.0, "milliohms", "milliohms")
kiloohms = ResistanceUnit(ohms, 1000.0, 0.0, 0.001, -0.0, "kiloohms", "kiloohms")

__all__ = ["ResistanceUnit", "ohms", "kilo_ohms", "milli_ohms", "nanoohms", "microohms", "milliohms", "kiloohms"]
