# THIS FILE WAS AUTO-GENERATED BY generate_units.py. DO NOT MODIFY

from typing import override

from smartunits import Unit, UnaryFunction
from smartunits.measures.solid_angle import SolidAngle



class SolidAngleUnit(Unit):
    __slots__ = (
        "_to_base_multiplier",
        "_to_base_offset",
        "_from_base_multiplier",
        "_from_base_offset",
    )
    _base_unit: "SolidAngleUnit"
    _to_base_multiplier: float
    _to_base_offset: float
    _from_base_multiplier: float
    _from_base_offset: float

    def __init__(
        self,
        base_unit: "SolidAngleUnit",
        to_base_multiplier: float,
        to_base_offset: float,
        from_base_multiplier: float,
        from_base_offset: float,
        name: str,
        symbol: str,
    ) -> None:
        super().__init__(base_unit, name, symbol)
        self._to_base_multiplier = to_base_multiplier
        self._to_base_offset = to_base_offset
        self._from_base_multiplier = from_base_multiplier
        self._from_base_offset = from_base_offset

    @override
    def get_base_unit(self) -> "SolidAngleUnit":
        return self._base_unit

    @override
    def of(self, magnitude: float):
        return SolidAngle.of(magnitude, self)

    @override
    def of_base_units(self, magnitude: float):
        return SolidAngle.of_base_units(magnitude, self)

    @override
    def zero(self):
        return self._zero

    @override
    def one(self):
        return self._one

    @override
    def per(self, other: Unit) -> Unit:
        t = type(other)

        from smartunits import PerUnit
        return PerUnit[SolidAngleUnit, t].combine(self, other)

    def __mul__(self, other: Unit) -> Unit:
        t = type(other)

        return NotImplemented

    @override
    def convert_from(self, magnitude: float, other_unit: "SolidAngleUnit") -> float:
        return self.from_base_units(other_unit.to_base_units(magnitude))

    @override
    def convert_to(self, magnitude: float, other_unit: "SolidAngleUnit") -> float:
        return other_unit.from_base_units(self.to_base_units(magnitude))

    @override
    def conversion_from(self, other_unit: "SolidAngleUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(other_unit.to_base_units(x)))

    @override
    def conversion_to(self, other_unit: "SolidAngleUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: other_unit.from_base_units(self.to_base_units(x)))

    @override
    def from_base_units(self, value_in_base_units: float) -> float:
        return value_in_base_units * self._from_base_multiplier + self._from_base_offset

    @override
    def to_base_units(self, value_in_native_units: float) -> float:
        return value_in_native_units * self._to_base_multiplier + self._to_base_offset

    @override
    def conversion_from_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(x))

    @override
    def conversion_to_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.to_base_units(x))


steradians = SolidAngleUnit(None, 1.0, 0.0, 1.0, -0.0, "steradians", "steradians")
nanosteradians = SolidAngleUnit(steradians, 1e-09, 0.0, 999999999.9999999, -0.0, "nanosteradians", "nanosteradians")
microsteradians = SolidAngleUnit(steradians, 1e-06, 0.0, 1000000.0, -0.0, "microsteradians", "microsteradians")
millisteradians = SolidAngleUnit(steradians, 0.001, 0.0, 1000.0, -0.0, "millisteradians", "millisteradians")
kilosteradians = SolidAngleUnit(steradians, 1000.0, 0.0, 0.001, -0.0, "kilosteradians", "kilosteradians")
degrees_squared = SolidAngleUnit(steradians, 0.00030461741978670857, 0.0, 3282.806350011744, -0.0, "degrees squared", "degrees squared")
spats = SolidAngleUnit(steradians, 12.566370614359172, 0.0, 0.07957747154594767, -0.0, "spats", "spats")

__all__ = ["SolidAngleUnit", "steradians", "nanosteradians", "microsteradians", "millisteradians", "kilosteradians", "degrees_squared", "spats"]
