# THIS FILE WAS AUTO-GENERATED BY generate_units.py. DO NOT MODIFY

from typing import override

from smartunits import Unit, UnaryFunction
from smartunits.measures.time import Time



class TimeUnit(Unit):
    __slots__ = (
        "_to_base_multiplier",
        "_to_base_offset",
        "_from_base_multiplier",
        "_from_base_offset",
    )
    _base_unit: "TimeUnit"
    _to_base_multiplier: float
    _to_base_offset: float
    _from_base_multiplier: float
    _from_base_offset: float

    def __init__(
        self,
        base_unit: "TimeUnit",
        to_base_multiplier: float,
        to_base_offset: float,
        from_base_multiplier: float,
        from_base_offset: float,
        name: str,
        symbol: str,
    ) -> None:
        super().__init__(base_unit, name, symbol)
        self._to_base_multiplier = to_base_multiplier
        self._to_base_offset = to_base_offset
        self._from_base_multiplier = from_base_multiplier
        self._from_base_offset = from_base_offset

    @override
    def get_base_unit(self) -> "TimeUnit":
        return self._base_unit

    @override
    def of(self, magnitude: float):
        return Time.of(magnitude, self)

    @override
    def of_base_units(self, magnitude: float):
        return Time.of_base_units(magnitude, self)

    @override
    def zero(self):
        return self._zero

    @override
    def one(self):
        return self._one

    @override
    def per(self, other: Unit) -> Unit:
        t = type(other)
        from .time_unit import TimeUnit
        if t is TimeUnit:
            from .dimensionless_unit import DimensionlessUnit
            return DimensionlessUnit.combine(self, other)

        from smartunits import PerUnit
        return PerUnit[TimeUnit, t].combine(self, other)

    def __mul__(self, other: Unit) -> Unit:
        t = type(other)

        return NotImplemented

    @override
    def convert_from(self, magnitude: float, other_unit: "TimeUnit") -> float:
        return self.from_base_units(other_unit.to_base_units(magnitude))

    @override
    def convert_to(self, magnitude: float, other_unit: "TimeUnit") -> float:
        return other_unit.from_base_units(self.to_base_units(magnitude))

    @override
    def conversion_from(self, other_unit: "TimeUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(other_unit.to_base_units(x)))

    @override
    def conversion_to(self, other_unit: "TimeUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: other_unit.from_base_units(self.to_base_units(x)))

    @override
    def from_base_units(self, value_in_base_units: float) -> float:
        return value_in_base_units * self._from_base_multiplier + self._from_base_offset

    @override
    def to_base_units(self, value_in_native_units: float) -> float:
        return value_in_native_units * self._to_base_multiplier + self._to_base_offset

    @override
    def conversion_from_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(x))

    @override
    def conversion_to_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.to_base_units(x))


seconds = TimeUnit(None, 1.0, 0.0, 1.0, -0.0, "second", "s")
milliseconds = TimeUnit(seconds, 0.001, 0.0, 1000.0, -0.0, "millisecond", "ms")
microseconds = TimeUnit(seconds, 1e-06, 0.0, 1000000.0, -0.0, "microsecond", "us")
nanoseconds = TimeUnit(seconds, 1e-09, 0.0, 999999999.9999999, -0.0, "nanosecond", "ns")
minutes = TimeUnit(seconds, 60.0, 0.0, 0.016666666666666666, -0.0, "minute", "min")
hours = TimeUnit(seconds, 3600.0, 0.0, 0.0002777777777777778, -0.0, "hour", "h")
kiloseconds = TimeUnit(seconds, 1000.0, 0.0, 0.001, -0.0, "kiloseconds", "kiloseconds")
days = TimeUnit(seconds, 86400.0, 0.0, 1.1574074074074073e-05, -0.0, "days", "days")
weeks = TimeUnit(seconds, 604800.0, 0.0, 1.6534391534391535e-06, -0.0, "weeks", "weeks")
years = TimeUnit(seconds, 31557600.0, 0.0, 3.168808781402895e-08, -0.0, "years", "years")
julian_years = TimeUnit(seconds, 31557600.0, 0.0, 3.168808781402895e-08, -0.0, "julian years", "julian years")
gregorian_years = TimeUnit(seconds, 31556952.0, 0.0, 3.168873850681143e-08, -0.0, "gregorian years", "gregorian years")

__all__ = ["TimeUnit", "seconds", "milliseconds", "microseconds", "nanoseconds", "minutes", "hours", "kiloseconds", "days", "weeks", "years", "julian_years", "gregorian_years"]
