# THIS FILE WAS AUTO-GENERATED BY generate_units.py. DO NOT MODIFY

from typing import override

from smartunits import Unit, UnaryFunction
from smartunits.measures.torque import Torque



class TorqueUnit(Unit):
    __slots__ = (
        "_to_base_multiplier",
        "_to_base_offset",
        "_from_base_multiplier",
        "_from_base_offset",
    )
    _base_unit: "TorqueUnit"
    _to_base_multiplier: float
    _to_base_offset: float
    _from_base_multiplier: float
    _from_base_offset: float

    def __init__(
        self,
        base_unit: "TorqueUnit",
        to_base_multiplier: float,
        to_base_offset: float,
        from_base_multiplier: float,
        from_base_offset: float,
        name: str,
        symbol: str,
    ) -> None:
        super().__init__(base_unit, name, symbol)
        self._to_base_multiplier = to_base_multiplier
        self._to_base_offset = to_base_offset
        self._from_base_multiplier = from_base_multiplier
        self._from_base_offset = from_base_offset

    @override
    def get_base_unit(self) -> "TorqueUnit":
        return self._base_unit

    @override
    def of(self, magnitude: float):
        return Torque.of(magnitude, self)

    @override
    def of_base_units(self, magnitude: float):
        return Torque.of_base_units(magnitude, self)

    @override
    def zero(self):
        return self._zero

    @override
    def one(self):
        return self._one

    @override
    def per(self, other: Unit) -> Unit:
        t = type(other)
        from .distance_unit import DistanceUnit
        if t is DistanceUnit:
            from .force_unit import ForceUnit
            return ForceUnit.combine(self, other)
        from .force_unit import ForceUnit
        if t is ForceUnit:
            from .distance_unit import DistanceUnit
            return DistanceUnit.combine(self, other)

        from smartunits import PerUnit
        return PerUnit[TorqueUnit, t].combine(self, other)

    def __mul__(self, other: Unit) -> Unit:
        t = type(other)

        return NotImplemented

    @override
    def convert_from(self, magnitude: float, other_unit: "TorqueUnit") -> float:
        return self.from_base_units(other_unit.to_base_units(magnitude))

    @override
    def convert_to(self, magnitude: float, other_unit: "TorqueUnit") -> float:
        return other_unit.from_base_units(self.to_base_units(magnitude))

    @override
    def conversion_from(self, other_unit: "TorqueUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(other_unit.to_base_units(x)))

    @override
    def conversion_to(self, other_unit: "TorqueUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: other_unit.from_base_units(self.to_base_units(x)))

    @override
    def from_base_units(self, value_in_base_units: float) -> float:
        return value_in_base_units * self._from_base_multiplier + self._from_base_offset

    @override
    def to_base_units(self, value_in_native_units: float) -> float:
        return value_in_native_units * self._to_base_multiplier + self._to_base_offset

    @override
    def conversion_from_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(x))

    @override
    def conversion_to_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.to_base_units(x))


newton_meters = TorqueUnit(None, 1.0, 0.0, 1.0, -0.0, "newton meter", "N m")
pound_feet = TorqueUnit(newton_meters, 1.3558179483314, 0.0, 0.7375621492772656, -0.0, "pound-foot", "lb ft")
pound_inches = TorqueUnit(newton_meters, 0.11298482902761667, 0.0, 8.850745791327187, -0.0, "pound-inch", "lb in")
ounce_inches = TorqueUnit(newton_meters, 0.007061551814226041, 0.0, 141.61193266123502, -0.0, "ounce-inch", "oz in")
foot_poundals = TorqueUnit(newton_meters, 0.0421401100938048, 0.0, 23.730360404231938, -0.0, "foot poundals", "foot poundals")
inch_pounds = TorqueUnit(newton_meters, 0.1129848290276167, 0.0, 8.850745791327185, -0.0, "inch pounds", "inch pounds")
meter_kilograms = TorqueUnit(newton_meters, 9.80665, 0.0, 0.10197162129779283, -0.0, "meter kilograms", "meter kilograms")

__all__ = ["TorqueUnit", "newton_meters", "pound_feet", "pound_inches", "ounce_inches", "foot_poundals", "inch_pounds", "meter_kilograms"]
