# THIS FILE WAS AUTO-GENERATED BY generate_units.py. DO NOT MODIFY

from typing import override

from smartunits import Unit, UnaryFunction
from smartunits.measures.volume import Volume



class VolumeUnit(Unit):
    __slots__ = (
        "_to_base_multiplier",
        "_to_base_offset",
        "_from_base_multiplier",
        "_from_base_offset",
    )
    _base_unit: "VolumeUnit"
    _to_base_multiplier: float
    _to_base_offset: float
    _from_base_multiplier: float
    _from_base_offset: float

    def __init__(
        self,
        base_unit: "VolumeUnit",
        to_base_multiplier: float,
        to_base_offset: float,
        from_base_multiplier: float,
        from_base_offset: float,
        name: str,
        symbol: str,
    ) -> None:
        super().__init__(base_unit, name, symbol)
        self._to_base_multiplier = to_base_multiplier
        self._to_base_offset = to_base_offset
        self._from_base_multiplier = from_base_multiplier
        self._from_base_offset = from_base_offset

    @override
    def get_base_unit(self) -> "VolumeUnit":
        return self._base_unit

    @override
    def of(self, magnitude: float):
        return Volume.of(magnitude, self)

    @override
    def of_base_units(self, magnitude: float):
        return Volume.of_base_units(magnitude, self)

    @override
    def zero(self):
        return self._zero

    @override
    def one(self):
        return self._one

    @override
    def per(self, other: Unit) -> Unit:
        t = type(other)

        from smartunits import PerUnit
        return PerUnit[VolumeUnit, t].combine(self, other)

    def __mul__(self, other: Unit) -> Unit:
        t = type(other)

        return NotImplemented

    @override
    def convert_from(self, magnitude: float, other_unit: "VolumeUnit") -> float:
        return self.from_base_units(other_unit.to_base_units(magnitude))

    @override
    def convert_to(self, magnitude: float, other_unit: "VolumeUnit") -> float:
        return other_unit.from_base_units(self.to_base_units(magnitude))

    @override
    def conversion_from(self, other_unit: "VolumeUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(other_unit.to_base_units(x)))

    @override
    def conversion_to(self, other_unit: "VolumeUnit") -> UnaryFunction:
        return UnaryFunction(lambda x: other_unit.from_base_units(self.to_base_units(x)))

    @override
    def from_base_units(self, value_in_base_units: float) -> float:
        return value_in_base_units * self._from_base_multiplier + self._from_base_offset

    @override
    def to_base_units(self, value_in_native_units: float) -> float:
        return value_in_native_units * self._to_base_multiplier + self._to_base_offset

    @override
    def conversion_from_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.from_base_units(x))

    @override
    def conversion_to_base_units(self) -> UnaryFunction:
        return UnaryFunction(lambda x: self.to_base_units(x))


cubic_meters = VolumeUnit(None, 1.0, 0.0, 1.0, -0.0, "cubic meters", "cubic meters")
cubic_millimeters = VolumeUnit(cubic_meters, 1e-09, 0.0, 999999999.9999999, -0.0, "cubic millimeters", "cubic millimeters")
cubic_kilometers = VolumeUnit(cubic_meters, 1000000000.0, 0.0, 1e-09, -0.0, "cubic kilometers", "cubic kilometers")
liters = VolumeUnit(cubic_meters, 0.001, 0.0, 1000.0, -0.0, "liters", "liters")
nanoliters = VolumeUnit(cubic_meters, 1e-12, 0.0, 1000000000000.0, -0.0, "nanoliters", "nanoliters")
microliters = VolumeUnit(cubic_meters, 1e-09, 0.0, 999999999.9999999, -0.0, "microliters", "microliters")
milliliters = VolumeUnit(cubic_meters, 1e-06, 0.0, 1000000.0, -0.0, "milliliters", "milliliters")
kiloliters = VolumeUnit(cubic_meters, 1.0, 0.0, 1.0, -0.0, "kiloliters", "kiloliters")
cubic_inches = VolumeUnit(cubic_meters, 1.6387064e-05, 0.0, 61023.74409473229, -0.0, "cubic inches", "cubic inches")
cubic_feet = VolumeUnit(cubic_meters, 0.028316846592000004, 0.0, 35.314666721488585, -0.0, "cubic feet", "cubic feet")
cubic_yards = VolumeUnit(cubic_meters, 0.764554857984, 0.0, 1.3079506193143922, -0.0, "cubic yards", "cubic yards")
cubic_miles = VolumeUnit(cubic_meters, 4168181825.44058, 0.0, 2.399127585789277e-10, -0.0, "cubic miles", "cubic miles")
gallons = VolumeUnit(cubic_meters, 0.003785411784, 0.0, 264.1720523581484, -0.0, "gallons", "gallons")
quarts = VolumeUnit(cubic_meters, 0.000946352946, 0.0, 1056.6882094325936, -0.0, "quarts", "quarts")
pints = VolumeUnit(cubic_meters, 0.000473176473, 0.0, 2113.376418865187, -0.0, "pints", "pints")
cups = VolumeUnit(cubic_meters, 0.0002365882365, 0.0, 4226.752837730374, -0.0, "cups", "cups")
fluid_ounces = VolumeUnit(cubic_meters, 2.95735295625e-05, 0.0, 33814.022701842994, -0.0, "fluid ounces", "fluid ounces")
barrels = VolumeUnit(cubic_meters, 0.158987294928, 0.0, 6.289810770432105, -0.0, "barrels", "barrels")
bushels = VolumeUnit(cubic_meters, 0.03523907016688, 0.0, 28.377593258401745, -0.0, "bushels", "bushels")
cords = VolumeUnit(cubic_meters, 3.624556363776, 0.0, 0.2758958337616296, -0.0, "cords", "cords")
cubic_fathoms = VolumeUnit(cubic_meters, 6.116438863872, 0.0, 0.16349382741429902, -0.0, "cubic fathoms", "cubic fathoms")
tablespoons = VolumeUnit(cubic_meters, 1.478676478125e-05, 0.0, 67628.04540368599, -0.0, "tablespoons", "tablespoons")
teaspoons = VolumeUnit(cubic_meters, 4.92892159375e-06, 0.0, 202884.136211058, -0.0, "teaspoons", "teaspoons")
pinches = VolumeUnit(cubic_meters, 6.1611519921875e-07, 0.0, 1623073.089688464, -0.0, "pinches", "pinches")
dashes = VolumeUnit(cubic_meters, 6.1611519921875e-07, 0.0, 1623073.089688464, -0.0, "dashes", "dashes")
drops = VolumeUnit(cubic_meters, 5e-08, 0.0, 20000000.0, -0.0, "drops", "drops")
fifths = VolumeUnit(cubic_meters, 0.0007570823568, 0.0, 1320.860261790742, -0.0, "fifths", "fifths")
drams = VolumeUnit(cubic_meters, 3.6966911953125e-06, 0.0, 270512.18161474395, -0.0, "drams", "drams")
gills = VolumeUnit(cubic_meters, 0.00011829411825, 0.0, 8453.505675460749, -0.0, "gills", "gills")
pecks = VolumeUnit(cubic_meters, 0.00880976754172, 0.0, 113.51037303360698, -0.0, "pecks", "pecks")
sacks = VolumeUnit(cubic_meters, 0.10568821050064, 0.0, 9.461793281039084, -0.0, "sacks", "sacks")
shots = VolumeUnit(cubic_meters, 4.436029434375e-05, 0.0, 22542.681801228664, -0.0, "shots", "shots")
strikes = VolumeUnit(cubic_meters, 0.07047814033376, 0.0, 14.188796629200873, -0.0, "strikes", "strikes")

__all__ = ["VolumeUnit", "cubic_meters", "cubic_millimeters", "cubic_kilometers", "liters", "nanoliters", "microliters", "milliliters", "kiloliters", "cubic_inches", "cubic_feet", "cubic_yards", "cubic_miles", "gallons", "quarts", "pints", "cups", "fluid_ounces", "barrels", "bushels", "cords", "cubic_fathoms", "tablespoons", "teaspoons", "pinches", "dashes", "drops", "fifths", "drams", "gills", "pecks", "sacks", "shots", "strikes"]
